### PR TITLE
Exactly 512 bytes docid fails

### LINKED ISSUE #5050: MDB_BAD_VALSIZE internal error for document ids of exactly 512 bytes.
**Describe the bug**
Sending a document with a docid with a length of exactly 512 bytes fails the task with an internal error referencing `MDB_BAD_VALSIZE`.

**To Reproduce**
1. Send the following document
```jsonc
[
  {
    "id": "totoaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  }
]
```
2. get the task, observe:
```jsonc
{
  "uid": 0,
  "indexUid": "mieli",
  "status": "failed",
  "type": "documentAdditionOrUpdate",
  "canceledBy": null,
  "details": {
    "receivedDocuments": 1,
    "indexedDocuments": 0
  },
  "error": {
    "message": "internal: MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size.",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
  },
  "duration": "PT0.037288S",
  "enqueuedAt": "2024-11-13T15:07:24.767537Z",
  "startedAt": "2024-11-13T15:07:24.769644Z",
  "finishedAt": "2024-11-13T15:07:24.806932Z"
}
```

**Expected behavior**
One of:
1. The task completes successfully, or
2. A user error is returned, pointing the document at fault.

**Meilisearch version:**
Reproduced in v1.10.3 and v1.11.0, likely to be older

**Additional context**
[Originating discussion](https://github.com/meilisearch/meilisearch/discussions/5014)

### PR DESCRIPTION
**Pull request by dureuill**
# Pull Request

## Related issue
Fixes #5050 

## What does this PR do?
- Return a user error rather than an internal one for docids of exactly 512 bytes
- Fix up error message to indicate that exactly 512 bytes long docids are not supported.
- Fix up error message to reflect that index uids are actually limited to 400 bytes in length

## Impact

- Impacts docs: 
    - update [this paragraph](https://www.meilisearch.com/docs/learn/resources/known_limitations#length-of-primary-key-values) to say 511 bytes instead of 512

### CODE REVIEW

File: crates/index-scheduler/src/error.rs [hunk 1]
```diff
@@ -103,7 +104,7 @@ pub enum Error {
     )]
     InvalidTaskCanceledBy { canceled_by: String },
     #[error(
-        "{index_uid} is not a valid index uid. Index uid can be an integer or a string containing only alphanumeric characters, hyphens (-) and underscores (_), and can not be more than 512 bytes."
+        "{index_uid} is not a valid index uid. Index uid can be an integer or a string containing only alphanumeric characters, hyphens (-) and underscores (_), and can not be more than 400 bytes."
```
Comment (irevoire) [inline crates/index-scheduler/src/error.rs:107]: Why 400 bytes?
Shouldn't it be 511 like the pk since it's stored as an lmdb key?

**Review by irevoire — APPROVED** [review]

**Comment by curquiza** [comment]
@dureuill since it impacts the docs, either
- could you open an issue to describe the change and ping doc team on it?
- update the current bug issue, ping the docs with the involved changes?

It's really not convenient for external teams to check PRs. They check issues.

Or since the change is really tiny, maybe we can open the docs PR directly?

As you wish!

File: crates/index-scheduler/src/error.rs (hunk 1 above)
Comment (dureuill) [reply crates/index-scheduler/src/error.rs:107]: this is what [the code is currently checking](https://github.com/meilisearch/meilisearch/blob/exactly-512-bytes-docid-fails/crates/dump/src/reader/v4/meta.rs#L43), so I'm just fixing the error message in that way.

Talking about it with @Kerollmops, the rationale was that at some point we might have wanted to include more things than just the index uid in the db key, or to include it with additional data as part of the key in another db.

I don't mind the 400 bytes limit, as that's already a super long index name. I mean `"Supercalifragilisticexpialidocious index with uid 30f61e7b-db93-4c76-937c-baeb5fa85a54 30f61e7b-db93-4c76-937c-baeb5fa85a54 30f61e7b-db93-4c76-937c-baeb5fa85a54` is only 160 bytes.

**Comment by dureuill** [comment]
Sure @curquiza, will open the docs PR and add the impacts doc label to the original issue

**Comment by dureuill** [comment]
@curquiza : opened https://github.com/meilisearch/documentation/pull/3071

**Review by Kerollmops — APPROVED** [review]
bors merge

**Comment by dureuill** [comment]
bors merge
