### PR TITLE
Fix index settings opt out

### LINKED ISSUE #5099: Opt-out settings routes for facet search and prefix search 404 in v1.12.0-rc.1
**Describe the bug**

Trying to use the `settings/facet-search` and `settings/prefix-search` routes in v1.12.0-rc.1 is returning a 404

**To Reproduce**
1. Run v1.12.0-rc.1
2. Create an index
3. Do a request on the `.../settings/facet-search` or `.../settings/prefix-search` routes

**Expected behavior**
The `get`, `put`, and `delete` routes should work for these settings.

**Screenshots**

**Meilisearch version:**
[e.g. v0.20.0]
v1.12.0-rc.1

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Pull Request

## Related issue
Fixes #5099 

## What does this PR do?
- Refactor the settings implementation ensuring the routes are configured
- Add a test checking if all the routes are tested
- Refactor the tests to ease the modifications

### CODE REVIEW

File: crates/meilisearch/src/routes/indexes/settings.rs [hunk 1]
```diff
@@ -17,6 +17,26 @@ use crate::extractors::authentication::GuardedData;
 use crate::routes::{get_task_id, is_dry_run, SummarizedTaskView};
 use crate::Opt;
 
+macro_rules! make_setting_routes {
```
Comment (Kerollmops) [inline crates/meilisearch/src/routes/indexes/settings.rs:20]: Can you add some comments/doc, please?

File: crates/meilisearch/tests/settings/get_settings.rs [hunk 2]
```diff
@@ -343,11 +304,10 @@ async fn error_update_setting_unexisting_index_invalid_uid() {
 }
 
 macro_rules! test_setting_routes {
```
Comment (Kerollmops) [inline crates/meilisearch/tests/settings/get_settings.rs:306]: Can you move this macro to the top of the file, please?

**Review by Kerollmops — CHANGES_REQUESTED** [review]

**Review by Kerollmops — APPROVED** [review]
bors merge
