### PR TITLE
Check all search filter attributes are filterable upfront

### LINKED ISSUE #5069: Filter error ignored on search request
**Describe the bug**
When searching using `POST /indexes/{indexUid}/search` there is a strange behavior when there is an error coming from the `filter` param. Depending on the `filter` object, sometimes, even if an error is present, Meilisearch just returns no documents without any error. It happens when adding more filter items in an array (creating AND), but does not seem linked to the number of filter items in the array, rather maybe the length of each independent filter item maybe.

**To Reproduce**
1. Index the movies dataset
2. Add `genres` as filterable

Try with these requests
```
req: POST /indexes/movies/search
params: {
  "facets": [
    "genres"
  ],
  "filter": [
    "test=test"
  ],
  "limit": 20
}
error: {
  "message": "Attribute `test` is not filterable. Available filterable attributes are: `genres`.\n1:5 test=test",
  "code": "invalid_search_filter",
  "type": "invalid_request",
  "link": "https://docs.meilisearch.com/errors#invalid_search_filter"
}
```
🔝 This is expected ✅ 
```
req: POST /indexes/movies/search
params: {
  "facets": [
    "genres"
  ],
  "filter": [
    "genres=\"Action\"",
    "test=test"
  ],
  "limit": 20
}
response: {
  "message": "Attribute `test` is not filterable. Available filterable attributes are: `genres`.\n1:5 test=test",
  "code": "invalid_search_filter",
  "type": "invalid_request",
  "link": "https://docs.meilisearch.com/errors#invalid_search_filter"
}
```
🔝 This is expected ✅ 

```
req: POST /indexes/movies/search
params: {
  "facets": [
    "genres"
  ],
  "filter": [
    "genres=\"Action\"",
    "genres=\"Adventure\"",
    "genres=\"Animation\"",
    "genres=\"Comedy\"",
    "test=test"
  ],
  "limit": 20
}
response: {
    "hits": [],
    "query": "",
    "processingTimeMs": 0,
    "limit": 20,
    "offset": 0,
    "estimatedTotalHits": 0,
    "facetDistribution": {
        "genres": {}
    },
    "facetStats": {}
}
```
🔝 This is not expected and the response should be the same as previous examples 🔴
 
**Expected behavior**
Meilisearch should respond an `error` if a `filter` is wrong, in all cases.

**Meilisearch version:**
v1.11.3

**Additional context**
Tested with the Meilisearch Cloud search preview

### PR DESCRIPTION
**Pull request by jameshiew**
# Pull Request

## Related issue
Fixes #5069

## What does this PR do?
- checks all `fid`s in the `Filter` tree are filterable before evaluating search query
- returns AttributeNotFilterable error if any are not

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

File: crates/milli/src/search/facet/filter.rs [hunk 1]
```diff
@@ -230,6 +230,15 @@ impl<'a> Filter<'a> {
     pub fn evaluate(&self, rtxn: &heed::RoTxn<'_>, index: &Index) -> Result<RoaringBitmap> {
         // to avoid doing this for each recursive call we're going to do it ONCE ahead of time
         let filterable_fields = index.filterable_fields(rtxn)?;
+        for fid in self.condition.fids(MAX_FILTER_DEPTH) {
```
Comment (jameshiew) [inline crates/milli/src/search/facet/filter.rs:233]: `fids()` is doing extra traversal of the `Filter` tree every search, so wasn't sure about this approach. Better might be to gather attributes to be checked during `Filter` construction (in [`Filter::from_str`](https://github.com/meilisearch/meilisearch/blob/b21d7aedf9096539041362d438e973a18170f3fc/crates/milli/src/search/facet/filter.rs#L210)), though it looked like it could involve a lot of refactoring

**Review by irevoire — APPROVED** [review]
Hey @jameshiew,

Yeah, it's not perfect, but that should do it.
Thanks a lot for looking into it, and sorry for the delay we took to review it.

bors merge

**Comment by irevoire** [comment]
bors merge

**Comment by jameshiew** [comment]
Thanks for reviewing and for building Meilisearch!

**Comment by curquiza** [comment]
bors merge
