### PR TITLE
ensure that the task queue is correctly imported

### LINKED ISSUE #3596: Tasks filter does not works with the dump
**Describe the bug**
After importing a dump, trying to query the task via a date filter doesn't works.

**To Reproduce**
1. Import a dump
2. Query the tasks via a date filter
3. Find nothing

**Expected behavior**
It works

**Screenshots**

**Meilisearch version:** v1.0.2 & v1.1.0 & main branch
It has been present since v0.30

### PR DESCRIPTION
**Pull request by irevoire**
## Related issue
Fixes #3596

I updated all the dump's integration tests to ensure that we're effectively able to query the tasks

### CODE REVIEW

File: index-scheduler/src/lib.rs [hunk 1]
```diff
@@ -987,6 +987,18 @@ impl IndexScheduler {
...
+        // we can't override the started_at & finished_at, so we must only set it if the tasks is finished and won't change
+        if matches!(task.status, Status::Succeeded | Status::Failed | Status::Canceled) {
+            if let Some(started_at) = task.started_at {
+                utils::insert_task_datetime(&mut wtxn, self.started_at, started_at, task.uid)?;
+            }
+            if let Some(finished_at) = task.finished_at {
+                utils::insert_task_datetime(&mut wtxn, self.finished_at, finished_at, task.uid)?;
+            }
+        }
+
```
Comment (Kerollmops) [inline index-scheduler/src/lib.rs:1001]: So this is it? We forgot to add a couple of lines. Nice catch @irevoire!

**Review by Kerollmops — APPROVED** [review]
I approve your work, tank you 🍐

**Comment by irevoire** [comment]
bors merge
