### PR TITLE
Fix _matchesPosition length calculate

### LINKED ISSUE #5429: _matchesPosition length calc with char length instead of byte
**Describe the bug**

https://github.com/meilisearch/meilisearch/blob/2500e3c06776c332b8566f9e5c8e1b34c4fff0ff/crates/milli/src/search/new/matches/mod.rs#L232-L233
**Expected behavior**

As [the document](https://www.meilisearch.com/docs/reference/api/search#show-matches-position) said that:

> start and length are measured in bytes and not the number of characters. For example, ü represents two bytes but one character.

I think either the code should be fixed or the documentation should be modified to avoid confusion.

**Meilisearch version:**

Latest

### PR DESCRIPTION
**Pull request by shaokeyibb**
# Pull Request

## Related issue
Fixes #5429 

## What does this PR do?
- It fixed #5429, which incorrectly using char length instead of byte length as result of `_matchesPosition`

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

File: crates/milli/src/search/new/matches/mod.rs [hunk 1]
```diff
@@ -229,8 +229,12 @@ impl<'t, 'tokenizer> Matcher<'t, 'tokenizer, '_, '_> {
...
                 .map(|m| MatchBounds {
                     start: tokens[m.get_first_token_pos()].byte_start,
-                    // TODO: Why is this in chars, while start is in bytes?
-                    length: m.char_count,
+                    length: (m.get_first_token_pos()..m.get_last_token_pos() + 1)
+                        .map(|i| tokens[i].clone())
+                        .flat_map(|token| token.char_map.clone().unwrap_or(vec![(1, 1); token.char_end - token.char_start] /* Some token doesn't have a char map, here we treat them as single byte chars. */))
+                        .map(|(original, _)| original as usize)
+                        .take(m.char_count)
+                        .sum(),
```
Comment (ManyTheFish) [inline crates/milli/src/search/new/matches/mod.rs:237]: We may avoid all these `clone()` and take the byte lengths of the characters when the char map is missing instead of counting 1 for each character.

```suggestion
                    length: (m.get_first_token_pos()..=m.get_last_token_pos())
                        .scan(m.char_count, |i, remaining_chars| {
                            let mut bytes = 0;
                            match &tokens[i].char_map {
                                Some(char_map) => {
                                  // iterate over the char map, retrieving the original bytes len
                                  for (original_bytes_in_char, _) in char_map {
                                    bytes += original_bytes_in_char;
                                    *remaining_chars -= 1;
                                  
                                    if remaining_chars == 0 {
                                      break;
                                    }
                                  }
                                }
                                None => {
                                  // iterate over the chars, retrieving the bytes len
                                  for c in tokens[i].lemma().chars() {
                                    bytes += c.len_utf8();
                                    *remaining_chars -= 1;
                                  
                                    if remaining_chars == 0 {
                                      break;
                                    }
                                  }
                                }
                              }
                            
                              bytes
                          })
                        .sum(),
```

But this should be put in a dedicated function to make the code cleaner.

**Comment by shaokeyibb** [comment]
Hi @ManyTheFish, here's the new implemention of byte length calculate without clone according to your code

**Review by ManyTheFish — APPROVED** [review]
