### PR TITLE
Fix some bugs for IndexSwap

### LINKED ISSUE #2969: Filtering tasks type by `indexSwap` return an error
**Describe the bug**

When I want to filter the tasks by the task type `indexSwap` I get an error.

**To Reproduce**

## Query

`GET /tasks?type=indexSwap`

## Response

```json
{
    "message": "Query deserialize error: `indexSwap` is not a type. Available types are `documentAdditionOrUpdate`, `documentDeletion`, `settingsUpdate`, `indexCreation`, `indexDeletion`, `indexUpdate`, `indexSwap`, `taskCancelation`, `taskDeletion`, `dumpExport`, `snapshot`.",
    "code": "bad_request",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#bad_request"
}
```

**Expected behavior**

I'm able to retrieve all `indexSwap` tasks

**Meilisearch version:** `v0.30.0-new-index-scheduler.beta.1`

### LINKED ISSUE #2972: Not specifying exactly 2 values for the `indexes` field during a swap returns a non helpful message.
**Describe the bug**

Not specifying exactly 2 values for the `indexes` field during a swap returns a non-helpful message.

Can we have a better `message` value with the `bad_request` `code`? 

**To Reproduce**

## Request

`POST`- `swap-indexes`

```json
[
    {
        "indexes": ["movies", "movies_new", "test"]
    }
]
```

## Response

```json
{
    "message": "The json payload provided is malformed. `trailing characters at line 3 column 39`.",
    "code": "malformed_payload",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#malformed_payload"
}
```

**Expected behavior**

The DX would be better with a message indicating exactly what is going on and helping the user to correct his request. 

**Meilisearch version:** `v0.30.0-new-index-scheduler.beta.1`

### LINKED ISSUE #2973: Specifying more than one index that do not exist during a swap operation does not return the variant message of `index_not_found` returning the list of non-existent indexes.
**Describe the bug**

Specifying more than an index that does not exist during a swap operation does not return the variant of `index_not_found` returning the list of non-existent indexes.

**To Reproduce**

Try to exchange several indexes that do not exist.

## Query

`POST`- `swap-indexes`

> `test2` and `test` do not exist.

```json
[
    {
        "swap": ["test2", "test"]
    }
]
```

## Task `error`

The asynchronous `error` is using the variant for a single missing index.

```json
"error": {
                "message": "Index `test2` not found.",
                "code": "index_not_found",
                "type": "invalid_request",
                "link": "https://docs.meilisearch.com/errors#index_not_found"
 },
```

**Expected behavior**

I should receive the message variant listing the indexes that do not exist.

```json
"error": {
                "message": "Indexes `test2`, `test` not found.",
                "code": "index_not_found",
                "type": "invalid_request",
                "link": "https://docs.meilisearch.com/errors#index_not_found"
 },
```

**Meilisearch version:** `v0.30.0-new-index-scheduler.beta.1`

### LINKED ISSUE #2975: Inconsistent behavior with other routes regarding `indexes` access when I'm trying to swap indexes I do not have access to
**Describe the bug**

When I use an API key that doesn't have access to an index I specify in a swap operation, I get a synchronous `index_not_found` error, whereas, in this type of case on other routes, it is an `invalid_api_key` error that is returned.

e.g. Trying to access `GET /indexes/B` while the API Key does not have access to it does not return an `index_not_found` but an `invalid_api_key` error instead.

I think we went a bit too fast in our error definition. For consistency, I think we should adopt the same behavior. 

**We could consider changing that later.**

**To Reproduce**

1. Create an API Key having the `action` `indexes.swap` and being able to access one of the two indexes to be swapped `["indexes": ["A"]`.

```json
{
            "name": "swap-key",
            "description": "Swap indexes",
            "key": "7193ddd98d380cb636a6c74674e8011885bbeef02c052ffac55f95816231d9ad",
            "uid": "f23127e0-4e4c-4968-b214-d2e397c59d76",
            "actions": [
                "indexes.swap"
            ],
            "indexes": [
                "A"
            ],
            "expiresAt": null,
            "createdAt": "2022-10-26T10:41:55.926719759Z",
            "updatedAt": "2022-10-26T10:41:55.926719759Z"
        }
```

2. Try to swap `A` and `B` using that API Key.
3. See the error response

```json
{
    "message": "Index `B` not found.",
    "code": "index_not_found",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#index_not_found"
}
```

**Expected behavior**

In this case, I would expect to receive an `invalid_api_key` error, as with the other routes.

```json
{
    "message": "The provided API key is invalid.",
    "code": "invalid_api_key",
    "type": "auth",
    "link": "https://docs.meilisearch.com/errors#invalid_api_key"
}
```

**Meilisearch version:** `v0.30.0-new-index-scheduler.beta.1`

### PR DESCRIPTION
**Pull request by loiclec**
## Related issues
Fixes #2973 , fixes #2972 , fixes #2975 , and fixes #2969 .

### CODE REVIEW

File: meilisearch-http/src/routes/swap_indexes.rs [hunk 1]
```diff
@@ -16,11 +16,10 @@ use crate::routes::tasks::TaskView;
 pub fn configure(cfg: &mut web::ServiceConfig) {
     cfg.service(web::resource("").route(web::post().to(SeqHandler(swap_indexes))));
 }
-
```
Comment (Kerollmops) [inline meilisearch-http/src/routes/swap_indexes.rs:19]: Why? ahahaha

File: meilisearch-http/src/routes/tasks.rs [hunk 2]
```diff
@@ -30,12 +32,30 @@ pub fn configure(cfg: &mut web::ServiceConfig) {
...
 }
 
+#[derive(Default, Debug, Clone, PartialEq, Serialize)]
+#[serde(untagged, rename_all = "camelCase")]
+pub enum IndexUidView {
+    Multiple(Vec<String>),
+    Single(String),
+    #[default]
+    None,
+}
```
Comment (Kerollmops) [inline meilisearch-http/src/routes/tasks.rs:42]:
```suggestion
}

```

File: meilisearch-types/src/tasks.rs [hunk 3]
```diff
@@ -383,6 +389,8 @@ impl FromStr for Kind {
             Ok(Kind::IndexCreation)
         } else if kind.eq_ignore_ascii_case("indexUpdate") {
             Ok(Kind::IndexUpdate)
+        } else if kind.eq_ignore_ascii_case("indexSwap") {
+            Ok(Kind::IndexSwap)
```
Comment (Kerollmops) [inline meilisearch-types/src/tasks.rs:393]: Would it be possible to do a match here? or something to be sure not to forget possible new variants?

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Thank you very much for all the fixes!

**Comment by Kerollmops** [comment]
BTW @irevoire, the test that doesn't pass is just broken due to your folder-formatter that is not outputting the files in a stable order. Maybe we can specify to walkdir that we want the result [ordered by file name](https://docs.rs/walkdir/latest/walkdir/struct.WalkDir.html#method.sort_by_file_name).

File: meilisearch-http/src/routes/swap_indexes.rs (hunk 1 above)
Comment (loiclec) [reply meilisearch-http/src/routes/swap_indexes.rs:19]: oh god I don't know how I always end up messing with the newlines 😭

File: meilisearch-types/src/tasks.rs (hunk 3 above)
Comment (Kerollmops) [reply meilisearch-types/src/tasks.rs:393]: I don't know if it's possible in fact as it is in the other order...

Comment (loiclec) [reply meilisearch-types/src/tasks.rs:393]: I don't know either :/

Comment (Kerollmops) [reply meilisearch-types/src/tasks.rs:393]: I am checking [the libraries that exist](https://lib.rs/search?q=from_str+enum) and that could be used as a proc macro to impl that for us instead of forgetting variants.
