### PR TITLE
Ranking fields should be stored and indexed by default

### LINKED ISSUE #521: asc/desc on string field
### Steps to reproduce
- Create an index with no primary-key given
- Add these settings on the sub-route `POST /indexes/:index_uid/settings/rankingRules`
```json
[
	"asc(title)",
	"typo"
]
```
- Add these documents with the route `POST /indexes/:index_uid/documents`
```json
[
  {
	"id": 1,
	"title": "Le Petit Prince",
	"author": "Exupéry"
  },
  {
  	"id": 2,
	"title": "Pride and Prejudice",
	"author": "Jane Austen"
  }
]
```
- Try to get documents with the routes `GET /indexes/:index_uid/documents` => There is no `title` displayed.

### Steps:
- [x] Fix in the code
- [x] Add test to test this issue

### PR DESCRIPTION
**Pull request by qdequele**
fix #521

### CODE REVIEW

File: meilisearch-core/src/update/settings_update.rs [hunk 1]
```diff
@@ -45,7 +45,13 @@ pub fn apply_settings_update(
     match settings.ranking_rules {
         UpdateState::Update(v) => {
             let ranked_field: Vec<&str> = v.iter().filter_map(RankingRule::field).collect();
-            schema.update_ranked(ranked_field)?;
+            schema.update_ranked(ranked_field.clone())?;
```
Comment (Kerollmops) [inline meilisearch-core/src/update/settings_update.rs]:
```suggestion
            schema.update_ranked(&ranked_field)?;
```

File: meilisearch-http/tests/settings_ranking_rules.rs [hunk 2]
```diff
@@ -135,3 +135,54 @@ fn send_malformed_custom_rule() {
...
+#[test]
+fn write_custom_ranking_and_index_documents() {
+    let mut server = common::Server::with_uid("movies");
+    let body = json!({
+        "uid": "movies",
+        "primaryKey": "id",
+    });
+    server.create_index(body);
+
+    // 1 - Add ranging rules with one custom rannking on a string
```
Comment (Kerollmops) [inline meilisearch-http/tests/settings_ranking_rules.rs]:
```suggestion
    // 1 - Add ranking rules with one custom ranking on a string
```
