### PR TITLE
Fix highlighting bug when searching for a phrase with cropping

### LINKED ISSUE #3975: Highlight is not working properly with cropping
**Describe the bug**
When I search for some words, `attributesToHighlight` is working well. But when I use `attributesToHighlight` with `attributesToCrop`, only the first word get highlighted.

**To Reproduce**
1. Insert this document:
```
{"id":2,"title":"test","overview":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."}
```
2. Search using:
```
client.index('movies').search('"eiusmod tempor"', {
  attributesToHighlight: ['overview'],
  attributesToCrop: ['overview'],
  cropLength: 20,
}).then((res) => {
  console.log(res.hits[0])
})
```
3. The output is:
```
{
  id: 2,
  title: 'test',
  overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  _formatted: {
    id: '2',
    title: 'test',
    overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do <em>eiusmod</em> tempor incididunt ut labore et dolore magna aliqua.'
  }
}
```
Please note that only "eiusmod" is highlighted.

**Expected behavior**
I expected both search words "eiusmod tempor" to be highlighted.
```
{
  id: 2,
  title: 'test',
  overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  _formatted: {
    id: '2',
    title: 'test',
    overview: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do <em>eiusmod</em> <em>tempor</em> incididunt ut labore et dolore magna aliqua.'
  }
}
```

**Screenshots**

**Meilisearch version:**
v1.3.0

### PR DESCRIPTION
**Pull request by vivek-26**
# Pull Request

## Related issue
Fixes #3975

## What does this PR do?
This PR -
- Fixes the bug where searching **only** for a phrase (containing multiple words) along with cropping, highlighted only the first word of the phrase.
- Adds unit test case for the above mentioned scenario.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by ManyTheFish — CHANGES_REQUESTED** [review]
Hello @vivek-26!

Thank you for contributing to Meilisearch, Your fix is a nice idea, however, it only partially fixes the issue, if you replace the query in your test by `"those \"and those\""` the word `those` is not highlighted.
I suggest making the changes in the `format` function (Lines 426 to 440 in matches/mod.rs), replacing the code by:
```rust
// If the text has to be cropped,
// crop around the best interval.
let (byte_start, byte_end) = match format_options.crop {
    Some(crop_size) if crop_size > 0 => {
        let matches = self.find_best_match_interval(matches, crop_size);
        self.crop_bounds(tokens, matches, crop_size)
    }
    _ => (0, self.text.len()),
};
```

Then, in the `for` loop a bit later (Line 453: `for m in matches {`) add an `if` case on the tokens' byte offsets, like:
```rust
// skip matches out of the crop window.
if token.byte_start < byte_start || token.byte_end > byte_end {
    continue;
}
```

Let me know if you need more information,

see you! ☺️

**Comment by vivek-26** [comment]
@ManyTheFish I have incorporated the requested changes. Requesting your review. Thank you!

**Review by ManyTheFish — CHANGES_REQUESTED** [review]
Perfect, a last small change in the test and it will be ready to be merged!

File: milli/src/search/new/matches/mod.rs [hunk 1]
```diff
@@ -800,6 +797,24 @@ mod tests {
...
+        let format_options = FormatOptions { highlight: true, crop: Some(10) };
+
+        let text = "The groundbreaking invention had the power to split the world between those who embraced progress and those who resisted change!";
+        let mut matcher = builder.build(text);
+        // should return 10 words with a marker at the start as well the end, and the highlighted matches.
+        insta::assert_snapshot!(
+            matcher.format(format_options),
+            @"…had the power to split <em>the</em> <em>world</em> between those who…"
+        );
+    }
```
[the remark this answers is not in the document]
Comment (vivek-26) [reply milli/src/search/new/matches/mod.rs]: added test case containing the query `"those \"and those\""`

File: milli/src/search/new/matches/mod.rs [hunk 2]
```diff
@@ -800,6 +797,32 @@ mod tests {
...
+            matcher.format(format_options),
+            @"…had the power to split <em>the</em> <em>world</em> between those who…"
+        );
+
+        let builder = MatcherBuilder::new_test(&rtxn, &temp_index, "those \"and those\"");
+        let mut matcher = builder.build(text);
+        // should highlight both "and" and "those".
+        insta::assert_snapshot!(
+            matcher.format(format_options),
+            @"…between those who embraced progress <em>and</em> <em>those</em> who resisted change…"
```
Comment (ManyTheFish) [inline milli/src/search/new/matches/mod.rs:822]: In my sense the first `those` should be highlighted, because it matches the first `those` 🤔 
```suggestion
            @"…between <em>those</em> who embraced progress <em>and</em> <em>those</em> who resisted change…"
```

Could you try to fix it, please? 😄

**Review by ManyTheFish — CHANGES_REQUESTED** [review]

File: milli/src/search/new/matches/mod.rs (hunk 2 above)
Comment (vivek-26) [reply milli/src/search/new/matches/mod.rs:822]: The logic looks correct. I created a new index and inserted this document:
```json
{
	"id": 1,
	"title": "test-pr",
	"overview": "The groundbreaking invention had the power to split the world between those who embraced progress and those who resisted change!"
}
```
Then, I ran a search for phrase `"those \"and those\""`:
```json
{
	"q": "those \"and those\"",
	"attributesToHighlight": [
		"overview"
	],
	"attributesToCrop": [
		"overview"
	],
	"cropLength": 10
}
```

I get the following response back, which highlights the first `those` as well the phrase `and those`:
```json
{
	"hits": [
		{
			"id": 1,
			"title": "test-pr",
			"overview": "The groundbreaking invention had the power to split the world between those who embraced progress and those who resisted change!",
			"_formatted": {
				"id": "1",
				"title": "test-pr",
				"overview": "…world between <em>those</em> who embraced progress <em>and</em> <em>those</em> who resisted…"
			}
		}
	],
	"query": "those \"and those\"",
	"processingTimeMs": 4,
	"limit": 20,
	"offset": 0,
	"estimatedTotalHits": 1
}
```

Comment (vivek-26) [reply milli/src/search/new/matches/mod.rs]: @ManyTheFish I created a new temporary index in the test and added the below document to it:
```json
{ "id": 1, "text": "The groundbreaking invention had the power to split the world between those who embraced progress and those who resisted change!" }
```
Now the test correctly highlights the first `those` as well the phrase `and those`.

Let me know if this correct or not 😅

**Comment by ManyTheFish** [comment]
Hello @vivek-26,
Perfect, a last thing, could you rebase on `release-v1.4.0`, please?

This way your fix will be available in the next version of Meilisearch that will be released in 2 weeks.
If you don't, your fix will only be released in 2 months. 😬 

Thank you for your contribution!

**Comment by vivek-26** [comment]
@ManyTheFish I have rebased on `release-v1.4.0` branch. Thanks for all the help!

**Comment by ManyTheFish** [comment]
Hello @vivek-26,
you have a small rogue commit in your PR: [Bump Swatinem/rust-cache from 2.5.1 to 2.6.2](https://github.com/meilisearch/meilisearch/pull/4028/commits/b0f3da05dd7af3dd38615091b24b02ddcde2ede5) could you drop it using `git rebase -i release-v1.4.0`, please?

**Comment by vivek-26** [comment]
Hey @ManyTheFish, I have removed the rogue bot commit.

**Comment by vivek-26** [comment]
Hi @ManyTheFish, requesting your review.

**Review by ManyTheFish — APPROVED** [review]
LGTM!
Thank you for your contribution, Your fix will be applied in v1.4 😁

bors merge
