### PR TITLE
Highlight align fix

### LINKED ISSUE #637: Highlight doesn't work correctly when specifying certain cropLength
as an example, when specifying `cropLength=30`, the highlighted word "insert" is not enclosed correctly by `<em></em>` tags (I'm getting `i<em>nsert </em>` instead of ` <em>insert</em>`)

```js
const message = {
  body: `well, it may not work like that, try the following: 
1. insert your trip
2. google your \`searchQuery\`
3. find a solution 
> say hello
`
}

fetch(`http://localhost:7700/indexes/messages/search?q=insert&attributesToHighlight=*&attributesToCrop=body&cropLength=30`)
// hits[0]._formatted.body 
// "that, try the following: i<em>nsert </em>your trip google your searchQuery"


fetch(`http://localhost:7700/indexes/messages/search?q=insert&attributesToHighlight=*&attributesToCrop=body&cropLength=80`)
// hits[0]._formatted.body 
// "well, it may not work like that, try the following: <em>insert</em> your trip google your searchQuery find a solution > dictatorship is good"

```

### PR DESCRIPTION
**Pull request by MarinPostma**
closes #637

### CODE REVIEW

File: meilisearch-http/src/helpers/meilisearch.rs [hunk 1]
```diff
@@ -482,12 +491,7 @@ fn calculate_highlights(
         }
     }
 
-    highlight_result
-}
-
-#[cfg(test)]
-mod tests {
-    use super::*;
+    highlight_result } #[cfg(test)] mod tests { use super::*;
```
Comment (Kerollmops) [inline meilisearch-http/src/helpers/meilisearch.rs:494]: Whooops

Comment (MarinPostma) [reply meilisearch-http/src/helpers/meilisearch.rs:494]: Ik ik 😁 it's fixed in local, with other things I'm trying to improve before starting review

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,6 @@
 ## v0.10.2
 
+  - Fix highlight align (#679)
```
Comment (Kerollmops) [inline CHANGELOG.md:3]:
```suggestion
  - Fix highlight miss-alignment (#679)
```
