### PR TITLE
Fix Total Hits being wrong when rankingScoreThreshold is used

### LINKED ISSUE #5274: Total Hits is wrong when there is rankingScoreThreshold
**Describe the bug**
`totalHits` returns normally returns the true count like the docs explain:

https://www.meilisearch.com/docs/guides/front_end/pagination#implementation-1

However, when `rankingScoreThreshold` is set, this changes. For pages below the true maximum page, totalHits returns the value as if there was no rankingScoreThreshold

In my case, without the threshold true totalHits count is `29.646` which Meili correctly returns as `totalHIts`. However, when I set `rankingScoreThreshold` to `0.95`, true count is `318` but Meili still returns `29.646` as `totalHIts` for the first page. Only if I try to query the 16th page which happens to be the last true page, then the true count is returned as `totalHits` which is `318`.

**To Reproduce**
1. Have a medium/large sized database
2. Set `maxTotalHits` to more than the size of records (I know this is quite unusual but valid in my case).
3. Query `page=1` without `rankingScoreThreshold` and check the `totalHits`.
4. Query `page=1` with a `rankingScoreThreshold` and check the `totalHits`.
5. Results won't be matching.

**Expected behavior**
I expect the actual exhaustive number of results to be returned regardless of the `rankingScoreThreshold` if `page` or `hitsPerPage` is set.

**Screenshots**

**Meilisearch version:**
v1.12

### PR DESCRIPTION
**Pull request by Mubelotix**
# Pull Request

## Related issue
Fixes #5274 

## What does this PR do?
This PR ensures the bucket_sort doesn't abort too early when using rankingScoreThreshold

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by Mubelotix** [comment]
I made some benchmarks to compare sorting performance of `/search` vs `/documents` and their results are very satisfying.

  | Range of documents | Placeholder | Documents | Speedup
-- | -- | -- | -- | --
without sort | 0-20 | 25.398 | 4.9652 | 80.45%
  | 0-500 | 27.754 | 6.1346 | 77.90%
  | 980-1000 | 25.245 | 5.3378 | 78.86%
  | 800000-800020 | 30.881 | 10.551 | 65.83%
sort on many different values | 0-20 | 194.86 | 178.08 | 8.61%
  | 0-500 | 388.6 | 280.34 | 27.86%
  | 980-1000 | 566.47 | 423.79 | 25.19%
  | 800000-800020 | 363130 | 265180 | 26.97%
sort on many similar values | 0-20 | 41.191 | 16.85 | 59.09%
  | 0-500 | 66.493 | 30.006 | 54.87%
  | 980-1000 | 73.202 | 34.782 | 52.48%
  | 800000-800020 | 7880.6 | 5915.3 | 24.94%
sort on many similar, then different | 0-20 | 186.62 | 155.27 | 16.80%
  | 0-500 | 3474.3 | 3320.1 | 4.44%
  | 980-1000 | 1575.2 | 1463 | 7.12%
  | 800000-800020 | 29738 | 18605 | 37.44%
sort on many different, then similar | 0-20 | 215.41 | 156.4 | 27.39%
  | 0-500 | 3533.5 | 3479.9 | 1.52%
  | 980-1000 | 1749.2 | 1487.8 | 14.94%
  | 800000-800020 | 30980 | 18897 | 39.00%
geo sort | 0-20 | 12241 | 11874 | 3.00%
  | 0-500 | 15251 | 14838 | 2.71%
  | 980-1000 | 18401 | 17590 | 4.41%
  | 800000-800020 | 31077000 | 4709500 | 84.85%
sort on many similar then geo sort | 0-20 | 109.86 | 81.245 | 26.05%
  | 0-500 | 740.64 | 812.5 | -9.70%
  | 980-1000 | 101980 | 101770 | 0.21%
  | 800000-800020 | 659060 | 621880 | 5.64%
sort on many different then geo sort | 0-20 | 201.89 | 176.16 | 12.74%
  | 0-500 | 459.32 | 339.52 | 26.08%
  | 980-1000 | 607.33 | 459.29 | 24.38%
  | 800000-800020 | 372800 | 281670 | 24.44%



Range of documents | Average speedup
-- | --
0-20 | 21.96%
0-500 | 15.40%
980-1000 | 18.39%
800000-800020 | 34.75%

File: crates/milli/src/search/new/bucket_sort.rs [hunk 1]
```diff
@@ -159,7 +161,12 @@ pub fn bucket_sort<'ctx, Q: RankingRuleQueryTrait>(
         };
     }
 
-    while valid_docids.len() < length {
+    let max_total_hits = max_total_hits.unwrap_or(usize::MAX);
```
Comment (dureuill) [inline crates/milli/src/search/new/bucket_sort.rs]: to avoid accidental full scans of the DB should `max_total_hits` somehow not be set, I advise we only take into account `exhaustive_number_hits` when `max_total_hits.is_some()`.

A nice way to express that could be the following:

```rust
let max_len_to_evaluate = match (max_total_hits, exhaustive_number_hits && ranking_score_threshold.is_some()) {
    (Some(max_total_hits), true) => max_total_hits,
    _ => length
};

while valid_docids.len() < max_len_to_evaluate {
// ...
}

**Review by dureuill — APPROVED** [review]
thank you!
