### PR TITLE
Optimize and fix task deletion

### LINKED ISSUE #5386: Sometime deleting tasks can take a very long time
**Describe the bug**
While looking at a client instance who was sending a ton of tasks (15M in total, 2M enqueued) the engine was trying to clean itself but was not very successful.
Between every processed tasks it would then enqueue a task deletion task (which is good), but sometime this task is taking more than one minute even though it’s doing almost nothing:
```json
    {
      "uid": 1396345,
      "progress": null,
      "details": {
        "providedIds": 0,
        "deletedDocuments": 0,
        "originalFilter": "\"id = '852032388'\""
      },
      "stats": {
        "totalNbTasks": 1,
        "status": {
          "succeeded": 1
        },
        "types": {
          "documentDeletion": 1
        },
        "indexUids": {
          "markets_v2": 1
        }
      },
      "duration": "PT122.229286467S",
      "startedAt": "2025-02-24T17:35:28.395360423Z",
      "finishedAt": "2025-02-24T17:37:30.62464689Z"
    },
    {
      "uid": 1396344,
      "progress": null,
      "details": {
        "matchedTasks": 36,
        "deletedTasks": 36,
        "originalFilter": "?beforeEnqueuedAt=2025-02-24T17:23:03.239754424Z&statuses=succeeded,failed,canceled"
      },
      "stats": {
        "totalNbTasks": 1,
        "status": {
          "succeeded": 1
        },
        "types": {
          "taskDeletion": 1
        },
        "indexUids": {}
      },
      "duration": "PT166.660293817S",
      "startedAt": "2025-02-24T17:29:38.241975013Z",
      "finishedAt": "2025-02-24T17:32:24.90226883Z"
    }
```

**Meilisearch version:**
v1.13.2

### LINKED ISSUE #5827: Some batches never get deleted
**Describe the bug**

The batch deletion task misses batches and those become phantom batches that exist in the db, can probably be retrieved, but are NOT listed among the list of batches.

**To Reproduce**

1. Register 2 tasks that get batched
2. Delete the first
3. Delete the second
4. The batch still exists!

Reproducing code:

```rust
// 1. We're going to autobatch 2 document addition
    // 2. We will delete the first task
    // 3. We will delete the second task
    // 4. The batch should be gone

    let (index_scheduler, mut handle) = IndexScheduler::test(true, vec![]);

    let mut tasks = Vec::new();
    for i in 0..2 {
        let content = format!(
            r#"{{
                    "id": {},
                    "doggo": "bob {}"
                }}"#,
            i, i
        );

        let (uuid, mut file) = index_scheduler.queue.create_update_file_with_uuid(i).unwrap();
        let documents_count = read_json(content.as_bytes(), &mut file).unwrap();
        file.persist().unwrap();
        let task = index_scheduler
            .register(
                KindWithContent::DocumentAdditionOrUpdate {
                    index_uid: S("doggos"),
                    primary_key: Some(S("id")),
                    method: ReplaceDocuments,
                    content_file: uuid,
                    documents_count,
                    allow_index_creation: true,
                },
                None,
                false,
            )
            .unwrap();
        tasks.push(task);
        index_scheduler.assert_internally_consistent();
    }

    handle.advance_one_successful_batch();
    let rtxn = index_scheduler.read_txn().unwrap();
    let batches = index_scheduler.queue.batches.all_batch_ids(&rtxn).unwrap();
    assert_eq!(batches.into_iter().collect::<Vec<_>>().as_slice(), &[0]);

    index_scheduler
        .register(
            KindWithContent::TaskDeletion {
                query: String::from("whatever"),
                tasks: RoaringBitmap::from_iter([tasks[0].uid]),
            },
            None,
            false,
        )
        .unwrap();
    handle.advance_one_successful_batch();
    let rtxn = index_scheduler.read_txn().unwrap();
    let batches = index_scheduler.queue.batches.all_batch_ids(&rtxn).unwrap();
    assert_eq!(batches.into_iter().collect::<Vec<_>>().as_slice(), &[0, 1]);

    index_scheduler
        .register(
            KindWithContent::TaskDeletion {
                query: String::from("whatever"),
                tasks: RoaringBitmap::from_iter([tasks[1].uid]),
            },
            None,
            false,
        )
        .unwrap();
    handle.advance_one_successful_batch();
    let rtxn = index_scheduler.read_txn().unwrap();
    let batches = index_scheduler.queue.batches.all_batch_ids(&rtxn).unwrap();
    assert_eq!(batches.into_iter().collect::<Vec<_>>().as_slice(), &[1, 2]);

    let batch0 = index_scheduler.queue.batches.get_batch(&rtxn, 0).unwrap();
    assert!(batch0.is_none(), "Batch 0 should have been deleted");
```

**Expected behavior**

A batch should be deleted once all its tasks have been deleted

**Screenshots**

**Meilisearch version:**

branch main

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

I'm already working on a fix, this is issue is just to keep track

### LINKED ISSUE #5832: Dumped tasks are disconnected from their batch
**Describe the bug**

Batch uids get set to null on all tasks when dumped.

https://github.com/meilisearch/meilisearch/blob/f4903c2fe7a06bfaaeac8f2b0969b5919d8cbea3/crates/index-scheduler/src/scheduler/process_dump_creation.rs#L86-L90

This should have been removed when #5247 was fixed.

**To Reproduce**

1. Perform a dump

**Expected behavior**

Batch uids should be stored

**Meilisearch version:**

branch main, all versions since v1.13

### PR DESCRIPTION
**Pull request by Mubelotix**
## Related issues

Fixes #5386
Fixes #5827 
Fixes #5832

## Changelog

We fixed longstanding bugs that caused Meilisearch to create orphan batches and to fail to delete tasks from the queue. This issue could stop users from inserting documents, changing settings, or creating indexes. Additionally, we significantly increased the speed of task deletion, thereby speeding up the automatic task deletion process by roughly 3 times.

## Performance

Before:

```
processing tasks                                               1225.000 ms
processing tasks > deleting batches                             794.035 ms
processing tasks > deleting batches > batch                     794.025 ms
processing tasks > deleting tasks                                30.805 ms
processing tasks > deleting tasks > task                         30.795 ms
processing tasks > deleting tasks date time                     398.535 ms
processing tasks > deleting tasks date time > task              398.510 ms
processing tasks > deleting tasks metadata                        0.040 ms
processing tasks > deleting tasks metadata > task                 0.016 ms
writing tasks to disk                                             0.289 ms
writing tasks to disk > task                                      0.253 ms
```

After:

```
processing tasks                                                444.015 ms
processing tasks > deleting batches                              26.260 ms
processing tasks > deleting batches > task                       26.250 ms
processing tasks > deleting batches date time                    48.080 ms
processing tasks > deleting batches metadata                      0.369 ms
processing tasks > deleting tasks                                24.475 ms
processing tasks > deleting tasks > task                         24.390 ms
processing tasks > deleting tasks date time                      89.060 ms
processing tasks > deleting tasks metadata                        0.014 ms
processing tasks > deleting tasks metadata > task                 0.008 ms
processing tasks > retrieving batch tasks                         8.835 ms
processing tasks > retrieving batch tasks > batch                 8.815 ms
processing tasks > retrieving tasks                             245.240 ms
processing tasks > retrieving tasks > task                      245.210 ms
writing tasks to disk                                             0.257 ms
writing tasks to disk > task                                      0.234 ms
```

I optimized it for deletion of many consecutive tasks. The task completes twice as fast in this case. It's probably a little slower for task deletions with few elements, but those were fast already

I think I got close to optimal performance. The bottleneck is lmdb throughput and there is nothing we can do about it.

@irevoire our initial idea of using a RoTxn first to read everything, and then switch to RwTxn to write everything isn't always the fastest. Sometimes it's better to do both at the same time because you benefit from the cache. I measured performance between every commit using the median over 30 samples and took decisions accordingly

The new algorithm scales beautifully when deleting a lot of consecutive tasks:

image

The previous algorithm was better at deleting few random tasks, but the difference is negligible

image

<details>
<summary>Here is my benchmarking script for reference</summary>

```py
import subprocess
import time
import requests
import json
import statistics
import os
import shutil
import tarfile
from pathlib import Path

# Config
MEILI_URL = "http://localhost:7700"
DATA_ARCHIVE = "data.ms.tar.gz"
NUM_RUNS = 30
WAIT_TIMEOUT = 120  # seconds

# Helper to parse duration strings to milliseconds
def parse_duration(value: str) -> float:
    if value.endswith("ms"):
        return float(value[:-2])
    elif value.endswith("µs"):
        return float(value[:-2]) / 1000
    elif value.endswith("ns"):
        return float(value[:-2]) / 1_000_000
    elif value.endswith("s"):
        return float(value[:-1]) * 1000
    return 0.0

# Wait until Meilisearch logs "listening"
def wait_until_listening(log_path, process, timeout=WAIT_TIMEOUT):
    start_time = time.time()
    while True:
        if process.poll() is not None:
            raise RuntimeError("Meilisearch exited unexpectedly.")
        try:
            with open(log_path, "r") as f:
                if "listening" in f.read():
                    return
        except Exception:
            pass
        if time.time() - start_time > timeout:
            process.terminate()
            raise TimeoutError("Timed out waiting for Meilisearch to start.")
        time.sleep(0.5)

# Extract data.ms.tar.gz into the given folder
def extract_data_archive(target_folder: Path):
    with tarfile.open(DATA_ARCHIVE, "r:gz") as tar:
        tar.extractall(path=target_folder.parent, filter="data")
    # Ensure extracted folder has expected name
    extracted = target_folder.parent / "data.ms"
    if extracted.exists():
        extracted.rename(target_folder)

# Collect timings
all_timings = {}

for run in range(1, NUM_RUNS + 1):
    print(f"\n🔁 Run {run}/{NUM_RUNS}")

    run_data_dir = Path(f"data{run}.ms")

    # Remove old DB for this run
    if run_data_dir.exists():
        shutil.rmtree(run_data_dir)

    # Extract fresh DB from archive
    extract_data_archive(run_data_dir)

    # Start Meilisearch pointing to the extracted data folder
    log_file = f"meili_run_{run}.log"
    with open(log_file, "w") as f:
        process = subprocess.Popen(
            ["cargo", "run", "--release", "--", "--db-path", str(run_data_dir), "--experimental-dumpless-upgrade"],
            stdout=f,
            stderr=subprocess.STDOUT,
        )

    try:
        time.sleep(1)  # give log file a moment to be created
        wait_until_listening(log_file, process)
        print("✅ Meilisearch is ready")
    except Exception as e:
        print(f"❌ Error: {e}")
        print(f"📄 --- Log output from run {run} ---")
        try:
            with open(log_file) as log:
                print(log.read())
        except FileNotFoundError:
            print("(log file not found)")
        process.terminate()
        continue

    # Send DELETE request
    try:
        delete_resp = requests.delete(f"{MEILI_URL}/tasks?uids=*")
        delete_resp.raise_for_status()
        task_uid = delete_resp.json().get("taskUid")
        if not task_uid:
            raise ValueError("No taskUid in DELETE response.")
    except Exception as e:
        print(f"❌ Failed to send DELETE: {e}")
        process.terminate()
        continue

    # Wait for task completion
    try:
        max_tries = 20
        for attempt in range(1, max_tries + 1):
            task_resp = requests.get(f"{MEILI_URL}/tasks/{task_uid}")
            task_resp.raise_for_status()
            task_status = task_resp.json().get("status")

            if task_status == "succeeded":
                print("✅ Task completed")
                break
            elif task_status == "failed":
                raise RuntimeError(f"Task {task_uid} failed")
            
            time.sleep(0.5)
        else:
            raise TimeoutError(f"Task {task_uid} not completed after {max_tries} tries")
    except Exception as e:
        print(f"❌ Error waiting for task completion: {e}")
        process.terminate()
        continue

    # Fetch batch details
    try:
        batch_resp = requests.get(f"{MEILI_URL}/batches?uids={task_uid}")
        batch_resp.raise_for_status()
        batch_data = batch_resp.json()
    except Exception as e:
        print(f"❌ Failed to fetch batch: {e}")
        process.terminate()
        continue

    # Kill Meilisearch
    process.terminate()
    process.wait()

    # Parse and store durations
    try:
        trace = batch_data["results"][0]["stats"].get("progressTrace")
        if not trace:
            raise ValueError("progressTrace not found in batch data")

        for key, val in trace.items():
            ms_val = parse_duration(val)
            all_timings.setdefault(key, []).append(ms_val)
    except Exception as e:
        print(f"❌ Failed to parse progress trace: {e}")
        print(f"📄 Raw batch data for run {run}:")
        print(json.dumps(batch_data, indent=2))

    # Remove log file
    if Path(log_file).exists():
        os.remove(log_file)

# Print final medians
print("\n📊 Median durations over successful runs (in ms):\n")
for key in sorted(all_timings.keys()):
    values = all_timings[key]
    median = statistics.median(values)
    print(f"{key:60} {median:>10.3f} ms")

```

```bash
#!/bin/bash

# Define Meilisearch URL
MEILISEARCH_URL="http://localhost:7700"
INDEX_NAME="movies"

# Document to send
DOCUMENT='[
  {
    "id": ID_PLACEHOLDER,
    "title": "Shazam",
    "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
    "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word.",
    "release_date": "2019-03-23"
  }
]'kkk

# Add 100 documents one by one
echo "Adding 100 documents to $INDEX_NAME..."
for i in $(seq 40000 100000); do
  DOC=$(echo "$DOCUMENT" | sed "s/ID_PLACEHOLDER/$i/")
  curl -s -X POST "$MEILISEARCH_URL/indexes/$INDEX_NAME/documents" \
    -H 'Content-Type: application/json' \
    --data-binary "$DOC" > /dev/null
done

echo "Finished adding documents."

# you then need to tar gz the folder
```
</details>

<details>
<summary>The graph script</summary>

```py
import subprocess
import time
import requests
import json
import os
import shutil
import tarfile
import random
from pathlib import Path

# Config
MEILI_URL = "http://localhost:7700"
DATA_ARCHIVE = "data.ms.tar.gz"
WAIT_TIMEOUT = 120  # seconds
N_VALUES = [round(i * 100_000 / 30) for i in range(30)]

def parse_duration(value: str) -> float:
    if value.endswith("ms"):
        return float(value[:-2])
    elif value.endswith("µs"):
        return float(value[:-2]) / 1000
    elif value.endswith("ns"):
        return float(value[:-2]) / 1_000_000
    elif value.endswith("s"):
        return float(value[:-1]) * 1000
    return 0.0

def wait_until_listening(log_path, process, timeout=WAIT_TIMEOUT):
    start_time = time.time()
    while True:
        if process.poll() is not None:
            raise RuntimeError("Meilisearch exited unexpectedly.")
        try:
            with open(log_path, "r") as f:
                if "listening" in f.read():
                    return
        except FileNotFoundError:
            pass
        if time.time() - start_time > timeout:
            process.terminate()
            raise TimeoutError("Timed out waiting for Meilisearch to start.")
        time.sleep(0.5)

def extract_data_archive(target_folder: Path):
    with tarfile.open(DATA_ARCHIVE, "r:gz") as tar:
        tar.extractall(path=target_folder.parent, filter="data")
    extracted = target_folder.parent / "data.ms"
    if extracted.exists():
        extracted.rename(target_folder)

def get_task_by_offset(offset):
    resp = requests.get(f"{MEILI_URL}/tasks?uids={offset}")
    resp.raise_for_status()
    hits = resp.json().get("results", [])
    if not hits:
        raise ValueError(f"No task found at offset {offset}")
    return hits[0]

# Main loop
for idx, n in enumerate(N_VALUES, 1):
    print(f"\n🔁 Run {idx}/20 — deleting {n} tasks")

    run_data_dir = Path(f"data_n{n}.ms")
    if run_data_dir.exists():
        shutil.rmtree(run_data_dir)
    extract_data_archive(run_data_dir)

    log_file = f"meili_run_n{n}.log"
    with open(log_file, "w") as f:
        process = subprocess.Popen(
            ["cargo", "run", "--release", "--", "--db-path", str(run_data_dir), "--experimental-dumpless-upgrade"],
            stdout=f,
            stderr=subprocess.STDOUT,
        )

    try:
        time.sleep(1)
        wait_until_listening(log_file, process)
        print("✅ Meilisearch is ready")
    except Exception as e:
        print(f"❌ Startup error: {e}")
        process.terminate()
        continue

    try:
        if n == 0:
            print("ℹ️ Skipping deletion because n=0")
            process.terminate()
            continue

        # Pick start offset
        start_offset = random.randint(0, 100_000 - n)

        start_task = get_task_by_offset(start_offset)
        end_task = get_task_by_offset(start_offset + n)

        start_time_val = start_task["enqueuedAt"]
        end_time_val = end_task["enqueuedAt"]

        # Perform delete by time range
        delete_resp = requests.delete(
            f"{MEILI_URL}/tasks",
            params={"afterEnqueuedAt": start_time_val, "beforeEnqueuedAt": end_time_val}
        )
        delete_resp.raise_for_status()
        task_uid = delete_resp.json().get("taskUid")
        if not task_uid:
            raise ValueError("No taskUid in DELETE response.")
    except Exception as e:
        print(f"❌ Failed to prepare or send DELETE: {e}")
        process.terminate()
        continue

    try:
        for _ in range(40):
            task_resp = requests.get(f"{MEILI_URL}/tasks/{task_uid}")
            task_resp.raise_for_status()
            status = task_resp.json().get("status")
            if status == "succeeded":
                print("✅ Deletion task completed")
                break
            elif status == "failed":
                raise RuntimeError(f"Task {task_uid} failed")
            time.sleep(0.5)
        else:
            raise TimeoutError("Task did not complete in time.")
    except Exception as e:
        print(f"❌ Error waiting for completion: {e}")
        process.terminate()
        continue

    try:
        batch_resp = requests.get(f"{MEILI_URL}/batches", params={"uids": task_uid})
        batch_resp.raise_for_status()
        batch_data = batch_resp.json()
        trace = batch_data["results"][0]["stats"].get("progressTrace", {})
        if trace:
            print("📊 Durations (ms):")
            for key, val in trace.items():
                print(f"  {key:60} {parse_duration(val):10.3f}")
        else:
            print("⚠️ No progress trace found")
    except Exception as e:
        print(f"❌ Failed to fetch batch: {e}")

    process.terminate()
    process.wait()

    if Path(log_file).exists():
        os.remove(log_file)
```

</details>

<details>
<summary>Random task graph script</summary>

```py
import subprocess
import time
import requests
import json
import os
import shutil
import tarfile
import random
from pathlib import Path

# Config
MEILI_URL = "http://localhost:7700"
DATA_ARCHIVE = "data.ms.tar.gz"
WAIT_TIMEOUT = 120  # seconds
N_VALUES = [round((i+1) * 300 / 30) for i in range(30)]

def parse_duration(value: str) -> float:
    if value.endswith("ms"):
        return float(value[:-2])
    elif value.endswith("µs"):
        return float(value[:-2]) / 1000
    elif value.endswith("ns"):
        return float(value[:-2]) / 1_000_000
    elif value.endswith("s"):
        return float(value[:-1]) * 1000
    return 0.0

def wait_until_listening(log_path, process, timeout=WAIT_TIMEOUT):
    start_time = time.time()
    while True:
        if process.poll() is not None:
            raise RuntimeError("Meilisearch exited unexpectedly.")
        try:
            with open(log_path, "r") as f:
                if "listening" in f.read():
                    return
        except FileNotFoundError:
            pass
        if time.time() - start_time > timeout:
            process.terminate()
            raise TimeoutError("Timed out waiting for Meilisearch to start.")
        time.sleep(0.5)

def extract_data_archive(target_folder: Path):
    with tarfile.open(DATA_ARCHIVE, "r:gz") as tar:
        tar.extractall(path=target_folder.parent, filter="data")
    extracted = target_folder.parent / "data.ms"
    if extracted.exists():
        extracted.rename(target_folder)

def get_task_by_offset(offset):
    resp = requests.get(f"{MEILI_URL}/tasks?uids={offset}")
    resp.raise_for_status()
    hits = resp.json().get("results", [])
    if not hits:
        raise ValueError(f"No task found at offset {offset}")
    return hits[0]

# Main loop
for idx, n in enumerate(N_VALUES, 1):
    print(f"\n🔁 Run {idx}/30 — deleting {n} random tasks")

    run_data_dir = Path(f"data_n{n}.ms")
    if run_data_dir.exists():
        shutil.rmtree(run_data_dir)
    extract_data_archive(run_data_dir)

    log_file = f"meili_run_n{n}.log"
    with open(log_file, "w") as f:
        process = subprocess.Popen(
            ["cargo", "run", "--release", "--", "--db-path", str(run_data_dir), "--experimental-dumpless-upgrade"],
            stdout=f,
            stderr=subprocess.STDOUT,
        )

    try:
        time.sleep(1)
        wait_until_listening(log_file, process)
        print("✅ Meilisearch is ready")
    except Exception as e:
        print(f"❌ Startup error: {e}")
        process.terminate()
        continue

    try:
        if n == 0:
            print("ℹ️ Skipping deletion because n=0")
            process.terminate()
            continue

        # Pick n random UIDs
        random_uids = random.sample(range(100_000), n)
        uids_param = ",".join(map(str, random_uids))

        # Perform delete by UID
        delete_resp = requests.delete(
            f"{MEILI_URL}/tasks",
            params={"uids": uids_param}
        )
        delete_resp.raise_for_status()
        task_uid = delete_resp.json().get("taskUid")
        if not task_uid:
            raise ValueError("No taskUid in DELETE response.")
    except Exception as e:
        print(f"❌ Failed to prepare or send DELETE: {e}")
        process.terminate()
        continue

    try:
        for _ in range(40):
            task_resp = requests.get(f"{MEILI_URL}/tasks/{task_uid}")
            task_resp.raise_for_status()
            status = task_resp.json().get("status")
            if status == "succeeded":
                print("✅ Deletion task completed")
                break
            elif status == "failed":
                raise RuntimeError(f"Task {task_uid} failed")
            time.sleep(0.5)
        else:
            raise TimeoutError("Task did not complete in time.")
    except Exception as e:
        print(f"❌ Error waiting for completion: {e}")
        process.terminate()
        continue

    try:
        batch_resp = requests.get(f"{MEILI_URL}/batches", params={"uids": task_uid})
        batch_resp.raise_for_status()
        batch_data = batch_resp.json()
        trace = batch_data["results"][0]["stats"].get("progressTrace", {})
        if trace:
            print("📊 Durations (ms):")
            for key, val in trace.items():
                print(f"  {key:60} {parse_duration(val):10.3f}")
        else:
            print("⚠️ No progress trace found")
    except Exception as e:
        print(f"❌ Failed to fetch batch: {e}")

    process.terminate()
    process.wait()

    if Path(log_file).exists():
        os.remove(log_file)

```

### CODE REVIEW

**Comment by Mubelotix** [comment]
So it doesn't really change the db but it will try to sweep databases for batches that should have been deleted but didn't because of #5827. This PR assumes it will land on 1.18

**Comment by curquiza** [comment]
⚠️Seen internally, do not merge this week (can be merged from August 25th)
https://meilisearch.slack.com/archives/C096Q9AGT47/p1755598140090899

File: crates/index-scheduler/src/utils.rs [hunk 1]
```diff
@@ -209,6 +209,24 @@ impl ProcessingBatch {
...
+            if it.peek().copied() != Some(curr + 1) {
+                let out = start.take().map(|s| s..=curr);
+                start = it.next();
+                return out;
+            }
+        }
+        start.take().map(|s| s..=s)
+    })
+}
+
```
Comment (Kerollmops) [inline crates/index-scheduler/src/utils.rs:235]: This function is bugguous, I'll fix it and everything will work again!

Comment (Kerollmops) [reply crates/index-scheduler/src/utils.rs:235]: Done, the issue was actually in **my rewrite** of this very function. It works now 🎉

**Review by Kerollmops — APPROVED** [review]
Hey @Mubelotix 👋

After a loOooOng time I was able to find a bit of time to rebase and reorganize these PR commits. Thank you very much for the original PR. We are finally merging it (and others too) 🎉

**Comment by Mubelotix** [comment]
Nice cleanup! I'm glad to see this is getting released 🎉
