### PR TITLE
Geo update bug

### LINKED ISSUE #5380: _geoPoint is not updated after updating the document's latitude and longitude
**Describe the bug**
After updating the longitude and latitude of the document, the sorting result is still the result before the last update.
It is still invalid to delete and then add the document that needs to be updated.
The sorting will be correct only if all documents are deleted and then added.

**To Reproduce**
1. Writing Data  `[
	{
    "id": 1,
	"title":"自治县",
	"_geo": {
		"lat":30.891258,
		"lng": 104.520486
	},
	"address":"四川省绵阳市北川羌族自治1县"
  },
  	{
    "id": 2,
	"title":"顶锅山",
	"_geo": {
		"lat":30.311173,
		"lng": 104.745925
	},
	"address":"四川省成都市新都区"
  },
  	{
    "id": 3,
	"title":"集三路",
	"_geo": {
		"lat":30.891292,
		"lng": 104.485115
	},
	"address":"金堂县栖贤梨花沟风景区"
  },
  	{
    "id": 4,
	"title":"前进村",
	"_geo": {
		"lat":30.1517,
		"lng": 103.483306
	},
	"address":"四川省成都市蒲江县前进路"
  }
]`
2. "_geoPoint(30.891292,104.435115):asc"   `{
			"id": 1,
			"title": "自治县",
			"_geo": {
				"lat": 30.891258,
				"lng": 104.520486
			},
			"address": "四川省绵阳市北川羌族自治1县",
			"_geoDistance": 8146,
			"_rankingScore": 1,
			"_rankingScoreDetails": {
				"_geoPoint(30.891292, 104.435115):asc": {
					"order": 0,
					"value": {
						"lat": 30.891258,
						"lng": 104.520486
					},
					"distance": 8146.2
				}
			}
		}`
3. When I update the data of document ID 1, the current document ranking will no longer be accurate. You can see that the last _geo  `{
			"id": 1,
			"title": "自治县",
			"_geo": {
				"lat": 31.891258,
				"lng": 104.520486
			},
			"address": "四川省绵阳市北川羌族自治1县",
			"_geoDistance": 111486,
			"_rankingScore": 1,
			"_rankingScoreDetails": {
				"_geoPoint(30.891292, 104.435115):asc": {
					"order": 0,
					"value": {
						"lat": 30.891258,
						"lng": 104.520486
					},
					"distance": 8146.2
				}
			}
		}`

**Expected behavior**
After updating the document _geo, I hope the sorting can also be handled correctly

**Screenshots**

Image

**Meilisearch version:**
1.13.2

### LINKED ISSUE #5399: _geoPoint with sort is not working
**Describe the bug**
When we try to sort by geopoint then it is giving this error. 

```
task 2097 panicked with message \"A geo faceted document doesn't contain any lat or lng\"
```

**To Reproduce**
1. Setup a index with sort-able with `_geo`
2. Search with sort filter on

```
_geoPoint($lat,$lng):asc
```

**Expected behavior**

**Screenshots**

Image

**Meilisearch version:**
[e.g. v2.33.1]

**Document**

```json
[
  {
    "id": "01JNTD0331TCA8HZTH0Z4J67FN",
    "name": "TEST",
    "description": "",
    "isActive": true,
    "rank": 0,
    "_geo": {
      "lat": 24.459525,
      "lng": 54.37524
    },
    "lat": "24.459525",
    "lng": "54.375240",
    "city": "TEST",
    "phone": "",
    "company": "",
    "province": "",
    "address_1": "Test",
    "address_2": "",
    "postal_code": "",
    "country_code": "in"
  },
  {
    "id": "01JNV356MZH5PDT95YTX74CX4V",
    "name": "TEST",
    "description": "",
    "isActive": true,
    "rank": 1,
    "_geo": {
      "lat": 25.171623,
      "lng": 55.312476
    },
    "lat": "25.171623",
    "lng": "55.312476",
    "city": "",
    "phone": "",
    "company": "",
    "province": "",
    "address_1": "",
    "address_2": "",
    "postal_code": "",
    "country_code": "in"
  }
]
```

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Pull Request

## Related issue
Fixes #5380
Fixes #5399

### CODE REVIEW

File: crates/milli/src/update/new/extract/faceted/extract_facets.rs [hunk 1]
```diff
@@ -130,7 +130,10 @@ impl FacetedDocidsExtractor {
                     rtxn,
                     index,
                     context.db_fields_ids_map,
-                )? {
+                )?;
+                let has_changed_for_geo_fields =
+                    inner.has_changed_for_geo_fields(rtxn, index, context.db_fields_ids_map)?;
+                if !has_changed && !has_changed_for_geo_fields {
```
Comment (irevoire) [inline crates/milli/src/update/new/extract/faceted/extract_facets.rs:136]: Nice, that’s easy to understand 👍

**Review by irevoire — APPROVED** [review]
Noice, the only test failing is a flaky test already fixed on main.

bors merge
