### PR TITLE
Fix settings bug

### LINKED ISSUE #942: Some Settings seem to be overwritten when documents are pushed after updating settings
**Describe the bug**
Some settings seem to be overwritten when documents are pushed after updating settings:
- `searchableAttributes`
- `displayedAttributes`

**To Reproduce**
I made a test on this branch:
https://github.com/LegendreM/MeiliSearch/commit/2d109cabbc798003f705a1f02d03ba0e6973f22e

**Expected behavior**
`searchableAttributes` and `displayedAttributes`should be unchanged.

**Additional context**
related to #891

### PR DESCRIPTION
**Pull request by MarinPostma**
fix #942, see https://github.com/meilisearch/MeiliSearch/issues/942#issuecomment-706266440

### CODE REVIEW

**Comment by MarinPostma** [comment]
bors try

File: meilisearch-core/src/serde/deserializer.rs [hunk 1]
```diff
@@ -93,7 +94,7 @@ impl<'de, 'a, 'b> de::Deserializer<'de> for &'b mut Deserializer<'a> {
                 };
 
                 let is_displayed = self.schema.is_displayed(attr);
-                if is_displayed && self.fields.map_or(true, |f| f.contains(&attr)) {
+                if !self.displayed || (is_displayed && self.fields.map_or(true, |f| f.contains(&attr))) {
```
Comment (LegendreM) [inline meilisearch-core/src/serde/deserializer.rs:97]: could you add a comment explaining this if statement please

File: meilisearch-schema/src/schema.rs [hunk 2]
```diff
@@ -159,18 +161,18 @@ impl Schema {
...
 
-    pub fn indexed(&self) -> Cow<[FieldId]> {
+    pub fn indexed(&self) -> Vec<FieldId> {
         match self.indexed {
-            OptionAll::Some(ref v) => Cow::Borrowed(v),
+            OptionAll::Some(ref v) => v.iter().cloned().collect(),
             OptionAll::All => {
                 let fields = self
-                    .fields_map
+                    .indexed_map
```
Comment (Kerollmops) [inline meilisearch-schema/src/schema.rs:169]: Why have you changed that? Was that a bug in the previous version?

File: meilisearch-schema/src/schema.rs [hunk 3]
```diff
@@ -204,15 +206,16 @@ impl Schema {
     pub fn set_indexed(&mut self, name: &str) -> SResult<(FieldId, IndexedPos)> {
         let id = self.fields_map.insert(name)?;
 
+        self.indexed = self.indexed.take().map(|mut v| {
+            v.insert(id);
+            v
+        });
+
```
Comment (Kerollmops) [inline meilisearch-schema/src/schema.rs:213]:
```suggestion
        if let Some(mut v) = self.indexed {
            v.insert(id);
        }

```

File: meilisearch-schema/src/schema.rs [hunk 4]
```diff
@@ -260,7 +263,13 @@ impl Schema {
             self.indexed = match self.indexed.take() {
                 // valid because indexed is All and indexed() return the content of
                 // indexed_map that is already updated
-                OptionAll::All => OptionAll::Some(self.indexed().into_owned()),
+                OptionAll::All => {
+                    let indexed = self.indexed_map
+                        .iter()
+                        .filter_map(|(&i, _)| if i != id { Some(i) } else { None })
+                        .collect();
+                    OptionAll::Some(indexed)
```
Comment (Kerollmops) [inline meilisearch-schema/src/schema.rs:271]: Are you just search for `id` in this `HashSet` ? Why not `get`ing it?

**Review by Kerollmops — CHANGES_REQUESTED** [review]

File: meilisearch-schema/src/schema.rs (hunk 2 above)
Comment (MarinPostma) [reply meilisearch-schema/src/schema.rs:169]: this is strictly equivalent in this context, but it seemed easier to understand this way

File: meilisearch-schema/src/schema.rs (hunk 4 above)
Comment (Kerollmops) [reply meilisearch-schema/src/schema.rs:271]: Whoops, no, you are search for all others, sorry, closing!

Comment (MarinPostma) [reply meilisearch-schema/src/schema.rs:271]: no, I am collecting all the fields in the indexed_map (`HashMap`) except the `id` one, and collect all this in a `HashSet`. I could collect all in an `HashSet` too and `HashSet::remove(id)` too:

```rust
                    let mut indexed: HashSet<_> = self.indexed_map
                        .keys()
                        .cloned()
                        .collect();
                    indexed.remove(&id);
                    OptionAll::Some(indexed)
```
do you prefer that?

Comment (Kerollmops) [reply meilisearch-schema/src/schema.rs:262]: I would maybe prefer you just `filter` on `keys` instead of a `filter_map`.

```rust
self.indexed_map
                        .keys()
                         .filter(|i| i != id)
                        .cloned()
                        .collect();
```

**Review by Kerollmops — CHANGES_REQUESTED** [review]
This is good, just use a filter instead and it's good for me :)

File: meilisearch-schema/src/schema.rs (hunk 4 above)
Comment (MarinPostma) [reply meilisearch-schema/src/schema.rs:262]: well well, turns out it isn't necessary:
```rust
            self.indexed_map.remove(&id);
```
is done just before

File: meilisearch-schema/src/schema.rs [hunk 5]
```diff
@@ -220,56 +220,6 @@ impl Schema {
...
-                },
-                OptionAll::Some(mut v) => {
-                    v.retain(|x| *x != id);
-                    OptionAll::Some(v)
-                }
-                OptionAll::None => OptionAll::None,
-            }
-        }
-    }
-
```
Comment (MarinPostma) [inline meilisearch-schema/src/schema.rs]: turns out it's dead code haha

Comment (Kerollmops) [reply meilisearch-schema/src/schema.rs]: Really, how is it possible?

Comment (MarinPostma) [reply meilisearch-schema/src/schema.rs]: those functions are too public, so rustc doesn't complain, we should use `pub(crate)` for everything that isn't exported out of the crate, I suppose

Comment (Kerollmops) [reply meilisearch-schema/src/schema.rs]: Okep, are they used by meilisearch-core or meilisearch-http, so?

Comment (MarinPostma) [reply meilisearch-schema/src/schema.rs]: nope it compiles and test pass

**Review by Kerollmops — CHANGES_REQUESTED** [review]
Seems good to me! Could you rebase or will bors do it by itself?

File: meilisearch-schema/src/schema.rs [hunk 6]
```diff
@@ -118,8 +110,10 @@ impl Schema {
                 Ok(id)
             }
             None => {
-                self.set_indexed(name)?;
-                self.set_displayed(name)
+                let id = self.fields_map.insert(name)?;
+                let pos = self.indexed_map.len() as u16;
+                self.indexed_map.insert(id, pos.into());
+                Ok(id)
```
Comment (LegendreM) [inline meilisearch-schema/src/schema.rs:116]: why `self.indexed` is no more updated here ?

Comment (MarinPostma) [reply meilisearch-schema/src/schema.rs:116]: this method is called whenever a new field is found. I want to add it to the known fields (`field_map`), and generate an indexed position for it, by inserting it in `indexed_map`. if I added it to  `indexed` too, then it would be considered an indexed field and this is what we do not want. I guess we could rename this method `add_known_field`, what do you think?

Comment (Kerollmops) [reply meilisearch-schema/src/schema.rs:116]: So what's the purpose of `indexed_map`? Why this name if this is not here to store the indexed fields?

Comment (Kerollmops) [reply meilisearch-schema/src/schema.rs:116]: Yeah, we can maybe find a better name than `insert_and_index`, indeed.

Comment (LegendreM) [reply meilisearch-schema/src/schema.rs:116]: I don't understand everything.

For a user we have 3 states for an attribute:
`indexed`: indexed in meilisearch but not used 
`displayed`: displayed in a search result
`searchable`: used when I search something

Internally their are:
`fields_map`
`indexed_map`
`indexed`
`displayed_map`

what is what ? 🤔

**Comment by MarinPostma** [comment]
- rename `indexed_map` into `field_positions`
- rename `insert_and_index` into `register_field`

File: meilisearch-schema/src/schema.rs [hunk 7]
```diff
@@ -158,7 +158,7 @@ impl Schema {
             OptionAll::Some(ref v) => v.iter().cloned().collect(),
             OptionAll::All => {
                 let fields = self
-                    .indexed_map
+                    .fields_position
                     .iter()
                     .map(|(&f, _)| f)
```
Comment (Kerollmops) [inline meilisearch-schema/src/schema.rs]: Is it just `fields_position.keys().cloned().collect()` here?

**Review by Kerollmops — CHANGES_REQUESTED** [review]

File: meilisearch-schema/src/schema.rs (hunk 7 above)
Comment (MarinPostma) [reply meilisearch-schema/src/schema.rs]: yes that's right, fixed

**Review by Kerollmops — APPROVED** [review]
Thank you, seems good to me! :)
