### PR TITLE
bug(lib): fix get dumps bad error code

### LINKED ISSUE #1994: v0.25.0 RC : wrong error when getting a invalid dump UID
Using rc0 (I also tried on [this branch](https://github.com/meilisearch/MeiliSearch/pull/1989)), when trying to get a dump with a UID that does not exist, I get

```json
{
    "message": "Dump `20201001-110357260` not found.",
    "code": "dump_process_failed",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#dump_process_failed"
}
```

I should get
```json
{
    "message": "Dump `20201001-110357260` not found.",
    "code": "dump_not_found",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#dump_not_found"
}
```

See: https://github.com/meilisearch/specifications/blob/develop/text/0061-error-format-and-definitions.md#dump_not_found

- [ ] fix bug
- [ ] 🔥 Add tests 🔥

### PR DESCRIPTION
**Pull request by MarinPostma**
fix bad error code being returned whet getting a dump status, and add a test
close #1994

### CODE REVIEW

File: meilisearch-http/tests/common/server.rs [hunk 1]
```diff
@@ -1,3 +1,4 @@
+#![allow(dead_code)]
```
Comment (Kerollmops) [inline meilisearch-http/tests/common/server.rs:1]: Why is there a `#[allow(dead_code)]` here? Can't the `get_dump_status` method be conditionally compiled?

**Review by Kerollmops — CHANGES_REQUESTED** [review]

**Review by curquiza — CHANGES_REQUESTED** [review]
The commits related to the CONTRIBUTING.md file should not be in this PR.

File: meilisearch-http/tests/common/server.rs (hunk 1 above)
Comment (MarinPostma) [reply meilisearch-http/tests/common/server.rs:1]: this is because the module is defined in the test file, and if the test file doesn't use all of the defined methods in the module, I get warnings. Overall all the methods are used, but in different test files.

**Review by Kerollmops — APPROVED** [review]
Looks good to me!

**Review by curquiza — APPROVED** [review]
💪 

bors merge

**Comment by MarinPostma** [comment]
Bors try

**Comment by curquiza** [comment]
Bors merge
