### PR TITLE
Remove hard coded task ids to prevent flaky tests

### LINKED ISSUE #4840: Improve the meilisearch integration tests
Hello, fellow contributors! Thanks for coming here 🌟 

In https://github.com/meilisearch/meilisearch/pull/4808, I started some work to make the test faster but didn't apply the techniques implemented to every test since there are so many of them, and that's where you can help us.

There are two tasks to do that I’ll highlight right below.

### Patching the `.wait_task(:task_id)`

A common pattern you'll see in the integration tests is that we create a task and then immediately wait for it by writing `.wait_task(0).await;` or any other number.
Here's an example: https://github.com/meilisearch/meilisearch/blob/abe128476fca60d683725f2598a365027ef5fbec/meilisearch/tests/tasks/mod.rs#L111-L134

This is really easy to get wrong and caused us a lot of flaky tests in the past; that's why we would like to get rid of all these calls and replace them with the actual task ID returned by Meilisearch.

For example, instead of doing:
```rust
    let index = server.index("test");
    index.create(None).await;
    index.wait_task(0).await;
```

We should write:
```rust
    let index = server.index("test");
    let (task, _code) = index.create(None).await;
    index.wait_task(task.uid()).await;
```

Also, did you notice how we're waiting for the task to finish, but then we don't check if it succeeded?
When the task was supposed to succeed in the tests, you should also call `.succeeded()` after waiting for the task:

```rust
    let index = server.index("test");
    let (task, _code) = index.create(None).await;
    index.wait_task(task.uid()).await.succeeded();
```

### Using a shared server when possible

A lot of tests are creating a new Meilisearch instance when they could instead share one with all the other tests.
The rules to know if a test can use a shared server are:
- It should use the default configuration; the server is initialized with `let server = Server::new().await;`
- It must **not** modify the global state of the index:
  - Don't add an API-key
  - Don't modify the features
  - Don't access indexes that are not yours
- ❗ An exception, though, is if the request is expected to fail in the test. For example, if the test try to delete an arbitrary index and then checks for its failure, in this case, we can implement a new method on the shared index, send the task, and ensure it fails; see this method for an example: https://github.com/meilisearch/meilisearch/blob/c45706936732aef16d5a07545e47534d59901a91/meilisearch/tests/common/server.rs#L218-L225

https://github.com/meilisearch/meilisearch/blob/abe128476fca60d683725f2598a365027ef5fbec/meilisearch/tests/search/geo.rs#L41-L63

This test, for example, only creates an index and modifies its content without altering any of the global state of the index.
We can update the server initialization from:
```rust
    let server = Server::new().await;
    let index = server.index("test");
```

To:

```rust
    let server = Server::new_shared().await;
    let index = server.unique_index(); // we cannot hardcode the name of an index; otherwise, we might have conflicts between tests
```

### Using a shared index when possible

The latest kind of big optimization possible is to reduce the number of times we index the same documents over and over again.
For example, if you look at this file: https://github.com/meilisearch/meilisearch/blob/abe128476fca60d683725f2598a365027ef5fbec/meilisearch/tests/search/geo.rs
You'll notice a common pattern: All the tests start by doing these operations and then do a single search request:
```rust
    let server = Server::new().await;
    let index = server.index("test");

    let documents = DOCUMENTS.clone();
    index.update_settings_filterable_attributes(json!(["_geo"])).await;
    index.update_settings_sortable_attributes(json!(["_geo"])).await;
    index.add_documents(documents, None).await;
    index.wait_task(2).await;
```

What we should do here is create a shared index between all these tests that index the documents only once and can then be used by everyone. Here's an example of how to do it: https://github.com/meilisearch/meilisearch/blob/c45706936732aef16d5a07545e47534d59901a91/meilisearch/tests/common/mod.rs#L200-L216

In this case, instead of creating a new set of `DOCUMENTS` and a new kind of `shared_index_with_geo` we could simply update the original `DOCUMENTS` set defined [here](https://github.com/meilisearch/meilisearch/blob/c45706936732aef16d5a07545e47534d59901a91/meilisearch/tests/common/mod.rs#L165-L198) and update then use the shared index function to get an index.

In the end, the test should look like this:

```rust
let index = shared_index_with_documents().await;

// The search requests
```

Once again, this optimization can only be applied to tests that don't modify the content of the index:
- Can't insert or update documents
- Can't delete documents
- Can't update the settings
- Can almost exclusively run searches, get documents, and stuff like that
- ❗ An exception, though, is if the request is expected to fail in the test. For example, if the test adds a wrong setting and then checks for its failure, in this case, we can implement a new method on the shared index that runs send the task and then ensures it fails; see this method for an example: https://github.com/meilisearch/meilisearch/blob/c45706936732aef16d5a07545e47534d59901a91/meilisearch/tests/common/index.rs#L259-L274

### The file to updates

Here's an almost exhaustive list of file that need to be updated:

- [ ] meilisearch/tests/auth/tenant_token.rs
- [ ] meilisearch/tests/auth/tenant_token_multi_search.rs
- [ ] meilisearch/tests/documents/add_documents.rs
- [ ] meilisearch/tests/documents/delete_documents.rs
- [ ] meilisearch/tests/documents/errors.rs
- [ ] meilisearch/tests/documents/get_documents.rs
- [ ] meilisearch/tests/documents/update_documents.rs
- [ ] meilisearch/tests/index/create_index.rs
- [ ] meilisearch/tests/index/delete_index.rs
- [ ] meilisearch/tests/index/get_index.rs
- [ ] meilisearch/tests/index/stats.rs
- [ ] meilisearch/tests/index/update_index.rs
- [ ] meilisearch/tests/search/errors.rs
- [ ] meilisearch/tests/search/facet_search.rs
- [ ] meilisearch/tests/search/formatted.rs
- [ ] meilisearch/tests/search/locales.rs
- [ ] meilisearch/tests/search/matching_strategy.rs
- [ ] meilisearch/tests/search/mod.rs
- [ ] meilisearch/tests/search/multi.rs
- [ ] meilisearch/tests/search/pagination.rs
- [ ] meilisearch/tests/search/restrict_searchable.rs
- [ ] meilisearch/tests/settings/distinct.rs
- [ ] meilisearch/tests/settings/get_settings.rs
- [ ] meilisearch/tests/settings/proximity_settings.rs
- [ ] meilisearch/tests/settings/tokenizer_customization.rs
- [ ] meilisearch/tests/stats/mod.rs
- [ ] meilisearch/tests/tasks/mod.rs

### What to do if I’m struggling

Please ping me and ask me questions on this issue; this will help others as well.

### PR DESCRIPTION
**Pull request by mhmoudr**
# Pull Request

## Related issue
Fixes partial #4840

## What does this PR do?
- Mainly scan the test code for any hard coded task Id and replace it by the returned task Id once the action or task is performed on an index.
- PS: _PR is not split by files as it has one theme applied to all tests which make it easy to review_ 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

File: crates/meilisearch/tests/auth/tenant_token.rs [hunk 1]
```diff
@@ -99,12 +99,12 @@ macro_rules! compute_authorized_search {
         server.use_admin_key("MASTER_KEY").await;
         let index = server.index("sales");
         let documents = DOCUMENTS.clone();
-        index.add_documents(documents, None).await;
-        index.wait_task(0).await;
-        index
+        let (task1,_status_code) = index.add_documents(documents, None).await;
+        index.wait_task(task1.uid()).await;
```
Comment (irevoire) [inline crates/meilisearch/tests/auth/tenant_token.rs:103]:
```suggestion
        index.wait_task(task1.uid()).await.succeeded();
```

**Review by irevoire — CHANGES_REQUESTED** [review]
Hey, it seems good to me.
After calling the `.wait_task` method, could also call the `.succeeded()` or `.failed()` method just so we're sure we got the expected status?
Otherwise, that doesn't entirely prevent the flaky tests.

Also, just wondering, did you use a tool like coccinelle or something else to generate this PR?

**Comment by mhmoudr** [comment]
Hey Thanks for review ... 
I have added the `.succeeded()` when possible, as in some calls the success check was performed manually after. 

PS1: tbh, I am not sure if this succeeded call will help stabilising the test as if the task have failed it is expected that the test will fail too, the earlier change was approaching the assumption about the task Ids which was hard coded/numbered everywhere in the test - happy to be corrected otherwise?

PS2: As for the change is was mostly find all and manual change as regx replace did play well for me in this case, many needed manual check.

**Comment by curquiza** [comment]
Hello @mhmoudr
can you fix the git conflicts?
We made a use release yesterday, so we brought a lot of new code on `main`

**Comment by mhmoudr** [comment]
Code is rebased to  latest origin/main.

**Comment by mhmoudr** [comment]
**Don't merge** the PR I just noticed a rebase problem (some code is unintentionally removed) ... I will fix later

**Comment by mhmoudr** [comment]
The rebase issue has been fixed, feel free to merge after review.

File: crates/meilisearch/tests/batches/mod.rs [hunk 2]
```diff
@@ -167,17 +168,18 @@ async fn list_batches_status_filtered() {
...
     let server = Server::new().await;
     let index = server.index("test");
-    let (task, _) = index.create(None).await;
-    index.wait_task(task.uid()).await.succeeded();
-    let (task, _) = index.delete().await;
+    let (task,_status_code) = index.create(None).await;
     index.wait_task(task.uid()).await.succeeded();
+    index
+        .add_documents(serde_json::from_str(include_str!("../assets/test_set.json")).unwrap(), None)
+        .await;
```
Comment (irevoire) [inline crates/meilisearch/tests/batches/mod.rs:175]: Hey, this test is wrong now.
I think it comes down to a bad rebase, it's one of the test that I recently updated because it was flaky (and it still is after your PR :sweat_smile:).
Can you put back my version here

File: crates/meilisearch/tests/batches/mod.rs [hunk 3]
```diff
@@ -1021,11 +1023,12 @@ async fn test_summarized_batch_cancelation() {
...
-    index.wait_task(0).await;
-    server.cancel_tasks("uids=0").await;
-    index.wait_task(1).await;
-    let (batch, _) = index.get_batch(1).await;
+    let (task,_status_code) = index.create(None).await;
+    index.wait_task(task.uid()).await.succeeded();
+    let (task,_status_code) = server.cancel_tasks("uids=0").await;
+    index.wait_task(task.uid()).await.succeeded();
+    //TODO: create a get_batch function interface that accepts u64, and remove the following cast.
+    let (batch, _) = index.get_batch(task.uid().to_u32().unwrap()).await;
```
Comment (irevoire) [inline crates/meilisearch/tests/batches/mod.rs:1031]: Hey, you're right that it would be better to retrieve the actual batch used in the task.
But we should definitely not use the task uid as a batch uid here.
Either we keep the previous version which was using a `1` or if you have the time you could add a method very similar to the `.uid()` but named `.batch_uid()` that returns the batch uid.
Feel free to also change the signature of the `get_batch` function so it can accept whatever you want, it's not really important. 
In the Meilisearch code it cannot accept anything else than a `u32` though.

**Review by irevoire — CHANGES_REQUESTED** [review]
Hey @mhmoudr it's awesome, I reviewed everything and I believe we're almost good to merge.
I left two small comments.
The CI is also broken because of a small warning, that should be easy to fix.
And from what I see you'll also need to run `cargo +nightly fmt` because a lot of formatting is wrong.

Then we should be good to merge :ok_hand: 
Thanks again for your interest in the project!

File: crates/meilisearch/tests/batches/mod.rs (hunk 2 above)
Comment (mhmoudr) [reply crates/meilisearch/tests/batches/mod.rs:175]: sure ... working on it

File: crates/meilisearch/tests/batches/mod.rs (hunk 3 above)
Comment (mhmoudr) [reply crates/meilisearch/tests/batches/mod.rs:1031]: I'v tried to get batch ID from the JSON payload but I was not able to find it in the returned string 


```
{
  "taskUid": 1,
  "indexUid": null,
  "status": "enqueued",
  "type": "taskCancelation",
  "enqueuedAt": "[date]"
}
```

my implementation was 
```
pub fn batch_uid(&self) -> u64 {
        if let Some(batch_uid) = self["batch_uid"].as_u64() {
            batch_uid
        } else if let Some(batch_uid) = self["batchUid"].as_u64() {
            batch_uid
        } else {
            panic!("Didn't find any task batch id in: {self}");
        }
    }
```

For now I will flip it back to hard coded values of 1 as it was, unless you have another suggestions.

**Comment by mhmoudr** [comment]
addressed all the mentioned issues, please review.

File: crates/meilisearch/tests/batches/mod.rs (hunk 3 above)
Comment (mhmoudr) [reply crates/meilisearch/tests/batches/mod.rs]: if interested in checking the error you can try pull changes from this commit (on a different branch): https://github.com/meilisearch/meilisearch/commit/0d380e005d2ef6c176afa7b23e47ce69082030f5

**Review by irevoire — CHANGES_REQUESTED** [review]
Hey, thanks for the update!
I still found a few strange things but we're almost good :thinking:

File: crates/meilisearch/tests/batches/mod.rs (hunk 3 above)
Comment (irevoire) [reply crates/meilisearch/tests/batches/mod.rs]: Hey, yeah, it's because the `batchUid` is only present when retrieving a task from the task queue and not when enqueuing a new task.
In your commit, the call to the task queue is made on the `.wait_task` so it should be updated to something like;
```rust
let task = server.wait_task(task.uid());
task.succeeded();
let batch = task.batch_uid(); // now that works
```

But no problem with keeping the hard coded values :+1:

File: crates/meilisearch/tests/documents/add_documents.rs [hunk 4]
```diff
@@ -1,4 +1,5 @@
 use actix_web::test;
+use actix_web::web::resource;
```
[the remark this answers is not in the document]
Comment (mhmoudr) [reply crates/meilisearch/tests/documents/add_documents.rs:2]: removed ..

File: crates/meilisearch/tests/batches/mod.rs [hunk 5]
```diff
@@ -170,14 +171,12 @@ async fn list_batches_type_filtered() {
     let (task, _) = index.create(None).await;
     index.wait_task(task.uid()).await.succeeded();
     let (task, _) = index.delete().await;
-    index.wait_task(task.uid()).await.succeeded();
-
```
[the remark this answers is not in the document]
Comment (mhmoudr) [reply crates/meilisearch/tests/batches/mod.rs]: Added back .. 
the previous rebase seems to have messed with may files :(

**Comment by ManyTheFish** [comment]
Hey @mhmoudr,
Let us know when you think the PR is ready to be reviewed again!

See you!

**Comment by mhmoudr** [comment]
Hi @ManyTheFish , 
It is ready for review ..  as I am trying to minimise the recent changes just to address any feedback on the PR

**Comment by ManyTheFish** [comment]
Hey @mhmoudr,
The test CI doesn't pass. Can you fix them before we can review your PR again, please? 😄 

`cargo test --locked --release --all` is the failing command ran by the CI.

I converted the PR to a draft; you can put it back as RFR when ready. This will let us know when we can review it.

Thank you!

**Review by irevoire — APPROVED** [review]
Hey @mhmoudr, 

We really need this PR merged, so I fixed the remaining issues myself.
Thanks again for your contribution :fire: 

bors merge
