### PR TITLE
Plural on task query

### LINKED ISSUE #3045: v0.30.0rc1 error code on cancel tasks not updated with new filters naming
**Describe the bug**
Between v0.30.0rc0 and v0.30.0rc1 some naming of filters were changed. For example `uid` to `uids`, `status` to `statuses`

Nonetheless, when providing `no` query parameters the error raised still has the old 

> Error: Meilisearch(MeilisearchError { error_message: "Query parameters to filter the tasks to cancel are missing. Available query parameters are: `uid`, `indexUid`, `status`, `type`.", error_code: MissingTaskFilters, error_type: InvalidRequest, error_link: "https://docs.meilisearch.com/errors#missing_task_filters" })

**To Reproduce**
1. `POST /tasks/cancel` without query parameters
2. Error raised is outdated

**Expected behavior**
The error should specify the correct queru parameters name. Also, 

**Screenshots**

**Meilisearch version:** [e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

### LINKED ISSUE #3046: v0.30.0rc1: missing new query filters in cancel tasks route (and maybe others)
**Describe the bug**
In v0.30.0rc0, new filters were added, for example: `before_enqueued_at`, `after_enqueued_at`, etc
These are not added in the error messages of `POST /tasks/cancel` (maybe other routes as well ?)

> Error: Meilisearch(MeilisearchError { error_message: "Query parameters to filter the tasks to cancel are missing. Available query parameters are: uid, indexUid, status, type.", error_code: MissingTaskFilters, error_type: InvalidRequest, error_link: "https://docs.meilisearch.com/errors#missing_task_filters" })

**To Reproduce**
1. `POST /tasks/cancel` without query parameters
2. Error raised is missing the other query parameters

**Expected behavior**
The error should specify the new query parameters

**Meilisearch version:** 
v0.30.0rc1

### PR DESCRIPTION
**Pull request by irevoire**
Fixes #3045 and fixes #3046

### CODE REVIEW

File: index-scheduler/src/error.rs [hunk 1]
```diff
@@ -60,9 +60,9 @@ pub enum Error {
     InvalidIndexUid { index_uid: String },
     #[error("Task `{0}` not found.")]
     TaskNotFound(TaskId),
-    #[error("Query parameters to filter the tasks to delete are missing. Available query parameters are: `uid`, `indexUid`, `status`, `type`.")]
+    #[error("Query parameters to filter the tasks to delete are missing. Available query parameters are: `uids`, `indexUids`, `statuses`, `types`, `beforeEnqueuedAt`, `afterEnqueuedAt`, `beforeStartedAt`, `afterStartedAt`, `beforeFinishedAt`, `afterFinishedAt`.")]
```
Comment (Kerollmops) [inline index-scheduler/src/error.rs:63]: It would be so good if we could do that without doing it by hand. [Using a crate](https://lib.rs/crates/field_names) that could return the serde-formatted names (camelCase).

File: meilisearch-http/tests/tasks/mod.rs [hunk 2]
```diff
@@ -173,6 +173,131 @@ async fn list_tasks_status_and_type_filtered() {
     assert_eq!(response["results"].as_array().unwrap().len(), 2);
 }
 
+#[actix_rt::test]
+async fn get_task_filter_error() {
+    let server = Server::new().await;
+
+    let (response, code) = server.tasks_filter(json!( { "lol": "pied" })).await;
```
Comment (Kerollmops) [inline meilisearch-http/tests/tasks/mod.rs:180]: Nice, I like this test 👁️🦶👁️

**Review by Kerollmops — APPROVED** [review]
I like what you've done here. Could you create an issue for the point I made about using a crate to retrieve the serde-formatted names, please?
bors merge
