### PR TITLE
Fix the cli flags related to the import of dump and snapshot.

### LINKED ISSUE #3238: Bug when importing dumps or snapshots
**Describe the bug**
When importing a dump with the `--ignore-dump-if-db-exists`, if the db exists, the flag is ignored.
Also, when using the `--ignore-snapshot-if-db-exists`, if an error occurred while opening the `data.ms`, the database was deleted.

### PR DESCRIPTION
**Pull request by irevoire**
Some flags were badly applied + the database wrongly deleted when it shouldn't.

To reduce the number of mistakes we might make I added a bunch of comments + created a function that handles the import of an existing or empty database.

Here is the associated (working) code from the v0.29.3: https://github.com/meilisearch/meilisearch/blob/release-v0.29.3/meilisearch-lib/src/dump/mod.rs#L166-L191

Fix  #3238

### CODE REVIEW

File: meilisearch-http/src/lib.rs [hunk 1]
```diff
@@ -108,105 +108,65 @@ pub fn create_app(
...
                     return Err(e);
                 }
             }
+        // the db already exists and we should not ignore the snapshot => throw an error
         } else if !empty_db && !opt.ignore_snapshot_if_db_exists {
             bail!(
                 "database already exists at {:?}, try to delete it or rename it",
                 opt.db_path.canonicalize().unwrap_or_else(|_| opt.db_path.to_owned())
             )
+        // the snapshot doesn't exists and we can't ignore it => throw an error
```
Comment (dureuill) [inline meilisearch-http/src/lib.rs:135]:
```suggestion
        // the snapshot doesn't exist and we can't ignore it => throw an error
```

File: meilisearch-http/src/lib.rs [hunk 2]
```diff
@@ -108,105 +108,65 @@ pub fn create_app(
...
         } else if !snapshot_path_exists && !opt.ignore_missing_snapshot {
             bail!("snapshot doesn't exist at {}", snapshot_path.display())
+        // the snapshot and the db exists, and we can ignore the snapshot because of the ignore_snapshot_if_db_exists flag
```
Comment (dureuill) [inline meilisearch-http/src/lib.rs:138]:
```suggestion
        // the snapshot and the db exist, and we can ignore the snapshot because of the ignore_snapshot_if_db_exists flag
```

File: meilisearch-http/src/lib.rs [hunk 3]
```diff
@@ -108,105 +108,65 @@ pub fn create_app(
...
                     return Err(e);
                 }
             }
+        // the db already exists and we should not ignore the dump option => throw an error
         } else if !empty_db && !opt.ignore_dump_if_db_exists {
             bail!(
                 "database already exists at {:?}, try to delete it or rename it",
                 opt.db_path.canonicalize().unwrap_or_else(|_| opt.db_path.to_owned())
             )
+        // the dump doesn't exists and we can't ignore it => throw an error
```
Comment (dureuill) [inline meilisearch-http/src/lib.rs:161]:
```suggestion
        // the dump doesn't exist and we can't ignore it => throw an error
```

File: meilisearch-http/src/lib.rs [hunk 4]
```diff
@@ -108,105 +108,65 @@ pub fn create_app(
...
         } else if !src_path_exists && !opt.ignore_missing_dump {
             bail!("dump doesn't exist at {:?}", path)
+        // the dump and the db exists and we can ignore the dump because of the ignore_dump_if_db_exists flag
```
Comment (dureuill) [inline meilisearch-http/src/lib.rs:164]:
```suggestion
        // the dump and the db exist and we can ignore the dump because of the ignore_dump_if_db_exists flag
        // or, the dump is missing but we can ignore that because of the ignore_missing_dump flag
```

**Review by dureuill — CHANGES_REQUESTED** [review]
Thanks for finding and fixing the bug so quickly!

Some typo + requested changes for clarity.

File: meilisearch-http/src/lib.rs [hunk 5]
```diff
@@ -228,6 +188,55 @@ pub fn setup_meilisearch(opt: &Opt) -> anyhow::Result<(Arc<IndexScheduler>, Auth
...
+        (Err(e), _, _) | (_, Err(e), _) | (_, _, Err(e)) => {
+            if matches!(on_failure, OnFailure::RemoveDb) {
+                std::fs::remove_dir_all(&opt.db_path)?;
+            }
+            Err(e)
+        }
+    }
+}
+
+fn start_or_import_existing_database(
```
[the remark this answers is not in the document]
Comment (irevoire) [reply meilisearch-http/src/lib.rs:229]: Oh yeah, right that's not super clear.
But no, we must call this function if there is no `data.ms` as well.

So... It should be used when there is an already existing `data.ms` that we want to serve directly to the user.
Or when we should create a new database :thinking: 

 `open_or_create_database`?

[the remark this answers is not in the document]
Comment (dureuill) [reply meilisearch-http/src/lib.rs:230]: Suggesting: 

`start_new_database` => `open_or_create_database_unchecked`
`start_or_import_existing_database` => `open_or_create_database`

**Review by dureuill — APPROVED** [review]
Reads much clearer to me with the new names! Thank you again for the PR.

bors merge

**Comment by Kerollmops** [comment]
Can we add a test in another PR, please?

**Comment by curquiza** [comment]
@Kerollmops isn't it related to https://github.com/meilisearch/meilisearch/issues/3239?
