### PR TITLE
Synonym unidecode

### LINKED ISSUE #964: Accents work strangely with synonyms
**Describe the bug**
I had some issues with some of the synonyms working and some not and it seems I managed to identify a bug.
It seems words with **accents** are not used from the synonym table (and/or the query is deaccentized before looking up synonyms (?))

**To Reproduce**
Add synonyms:

["case"]: ["holder"] --> works (searches for holder with queries both "case" and "cáse"!)
["cáse"]: ["holder"] --> does not work (for either)

**Expected behavior**
In a previous issue (#949) it was mentioned there is no typo tolerance with synonyms, however it now seems when considering synonyms, there is some sort of deaccenting the query before looking up in the synonyms table (?)

### PR DESCRIPTION
**Pull request by MarinPostma**
fix #964 

- unidecodes all synonyms before adding them to the synonyms fst
- stores a copy of the original synonyms (unicoded) for later retrieve

### CODE REVIEW

File: meilisearch-core/src/store/main.rs [hunk 1]
```diff
@@ -28,6 +28,7 @@ const SCHEMA_KEY: &str = "schema";
 const SORTED_DOCUMENT_IDS_CACHE_KEY: &str = "sorted-document-ids-cache";
 const STOP_WORDS_KEY: &str = "stop-words";
 const SYNONYMS_KEY: &str = "synonyms";
+const SYNONYMS_UNICASED_KEY: &str = "synonyms-unicased";
```
Comment (qdequele) [inline meilisearch-core/src/store/main.rs:31]: Why do you keep both?

Comment (MarinPostma) [reply meilisearch-core/src/store/main.rs:31]: so the synonyms retrieved are the same as the one that were put in

Comment (LegendreM) [reply meilisearch-core/src/store/main.rs:31]: I think we should transparently assume that we transform synonyms, no ?

lets say I add,
```
"synonyms": {
            "wolverine": ["xmen", "logan"],
            "wolvérine": ["filin", "toto"]
        }
```

It will be displayed as:

```
"synonyms": {
            "wolverine": ["xmen", "logan"],
            "wolvérine": ["filin", "toto"]
        }
```

but behave as:

```
"synonyms": {
            "wolverine": ["xmen", "logan", "filin", "toto"]
        }
```

am I right ?

File: meilisearch-core/src/store/synonyms.rs [hunk 2]
```diff
@@ -1,40 +1,55 @@
...
+        self.synonyms_unicased.put(writer, word, &synonyms_vec)?;
+        Ok(())
     }
 
-    pub fn del_synonyms(self, writer: &mut heed::RwTxn<MainT>, word: &[u8]) -> ZResult<bool> {
-        self.synonyms.delete(writer, word)
+    pub fn del_synonyms(self, writer: &mut heed::RwTxn<MainT>, word: &str) -> ZResult<bool> {
+        let deunicoded = deunicode(word);
+        self.synonyms_unicased.delete(writer, word)?;
+        self.synonyms.delete(writer, deunicoded.as_bytes())
```
Comment (LegendreM) [inline meilisearch-core/src/store/synonyms.rs:31]: this function is never used

**Review by LegendreM — CHANGES_REQUESTED** [review]

File: meilisearch-core/src/store/main.rs (hunk 1 above)
Comment (MarinPostma) [reply meilisearch-core/src/store/main.rs:31]: uhmm, I hadn't thought of that. It actually replace the old one, but we would expect it to behave as:
```
"synonyms": {
            "wolverine": ["xmen", "logan", "filin", "toto"]
        }
```
indeed. This does not answer your question though... What are your opinions @curquiza @qdequele @Kerollmops ?

Comment (Kerollmops) [reply meilisearch-core/src/store/main.rs:31]: I am more on the many side here, I prefer when behaviors are explicit, and here we will 1. remove some code and 2. make it explicit to the user that we always transform syninyms.

Comment (MarinPostma) [reply meilisearch-core/src/store/main.rs:31]: and what should be the behaviour of this?
```
"synonyms": {
            "wolverine": ["xmen", "logan"],
            "wolvérine": ["filin", "toto"]
        }
```

Comment (Kerollmops) [reply meilisearch-core/src/store/main.rs:31]: I think we should just merge them as wolverine is the same as wolvérine for the engine, for now at least, maybe in the future we will change that (e.g. for chinese, thaï).

Comment (curquiza) [reply meilisearch-core/src/store/main.rs:31]: Hello sorry for the delay!
I agree with Kero and Many for the moment, maybe it's better to assume this behaviorm for a first try.

**Comment by MarinPostma** [comment]
final implemetation:
- the synonyms are deunicoded and merged if their deunicoded representation are equal
- the merged synonyms arrays are not sorted (this could be part of another PR, if we decide that we need it)

**Review by LegendreM — APPROVED** [review]

File: meilisearch-core/src/update/settings_update.rs [hunk 3]
```diff
@@ -138,6 +138,23 @@ pub fn apply_settings_update(
     Ok(())
 }
 
+fn transform_synonyms(synonyms: BTreeMap<String, Vec<String>>) -> BTreeMap<String, Vec<String>> {
```
Comment (Kerollmops) [inline meilisearch-core/src/update/settings_update.rs:141]:
```suggestion
fn canonicalize_synonyms(synonyms: BTreeMap<String, Vec<String>>) -> BTreeMap<String, Vec<String>> {
```

File: meilisearch-core/src/update/settings_update.rs [hunk 4]
```diff
@@ -138,6 +138,23 @@ pub fn apply_settings_update(
...
+        .fold(BTreeMap::new(), |mut map, (key, values)| {
+            let deunicoded = deunicode::deunicode(&key);
+            match map.entry(deunicoded) {
+                Entry::Vacant(entry) => {
+                    entry.insert(values);
+                }
+                Entry::Occupied(mut entry) => {
+                    entry.get_mut().extend_from_slice(&values);
+                }
+            }
```
Comment (Kerollmops) [inline meilisearch-core/src/update/settings_update.rs:153]:
```suggestion
            map.entry(deunicoded).or_default().extend_from_slice(&values);
```

File: meilisearch-core/src/update/settings_update.rs [hunk 5]
```diff
@@ -138,6 +138,23 @@ pub fn apply_settings_update(
     Ok(())
 }
 
+fn transform_synonyms(synonyms: BTreeMap<String, Vec<String>>) -> BTreeMap<String, Vec<String>> {
+    synonyms
+        .into_iter()
+        .fold(BTreeMap::new(), |mut map, (key, values)| {
```
Comment (Kerollmops) [inline meilisearch-core/src/update/settings_update.rs:144]: I am not a big fan 💨 of this `fold`, I would highly prefer a for loop for readability but if you think I am wrong, keep it :)

**Review by Kerollmops — CHANGES_REQUESTED** [review]

File: meilisearch-core/src/update/settings_update.rs (hunk 4 above)
Comment (Kerollmops) [reply meilisearch-core/src/update/settings_update.rs:153]: And you can remove the `btree_map::Entry` import.

File: meilisearch-core/src/update/settings_update.rs (hunk 5 above)
Comment (MarinPostma) [reply meilisearch-core/src/update/settings_update.rs:144]: I don't mind, I like fold, but I prefer readability

**Review by Kerollmops — APPROVED** [review]

File: meilisearch-core/src/update/settings_update.rs [hunk 6]
```diff
@@ -138,6 +138,15 @@ pub fn apply_settings_update(
     Ok(())
 }
 
+fn canonicalize_synonyms(synonyms: BTreeMap<String, Vec<String>>) -> BTreeMap<String, Vec<String>> {
+    let mut canonicalized: BTreeMap<String, Vec<String>> = BTreeMap::new();
```
Comment (Kerollmops) [inline meilisearch-core/src/update/settings_update.rs:142]:
```suggestion
    let mut canonicalized = BTreeMap::new();
```

**Review by Kerollmops — CHANGES_REQUESTED** [review]

File: meilisearch-core/src/update/settings_update.rs [hunk 7]
```diff
@@ -138,6 +138,18 @@ pub fn apply_settings_update(
...
 }
 
+fn canonicalize_synonyms(synonyms: BTreeMap<String, Vec<String>>) -> BTreeMap<String, Vec<String>> {
+    let mut canonicalized = BTreeMap::new();
+    for (key, values) in synonyms {
+        let deunicoded = deunicode::deunicode(&key);
+        canonicalized
+            .entry(deunicoded)
+            .or_insert_with(Vec::new)
+            .extend_from_slice(&values);
```
Comment (Kerollmops) [inline meilisearch-core/src/update/settings_update.rs:148]: Wow!

bors r+

**Review by Kerollmops — APPROVED** [review]
