### PR TITLE
Fix mini dashboard

### LINKED ISSUE #1750: The mini-dashboard does not work anymore
**Describe the bug**
The mini dashboard does not work anymore.

**To Reproduce**
Steps to reproduce the behaviour:
1. `cargo run`
2. Open your browser on `localhost:7700`

**Expected behaviour**
It works

**Screenshots**
image

**MeiliSearch version:** main

### PR DESCRIPTION
**Pull request by anirudhRowjee**
This commit is a fix to issue #1750.
As a part of the changes to solve this issue, the following changes have
been made -
1. Route registration for static assets has been modified
2. the `mut` keyword on the `scope` has been removed.

### CODE REVIEW

**Review by curquiza — DISMISSED** [review]
Thank you so much for this fix!!
I tested, it works 😄 

We wait for the Marin's approval before any merge 🙂

File: meilisearch-http/src/lib.rs [hunk 1]
```diff
@@ -147,7 +147,7 @@ pub fn dashboard(config: &mut web::ServiceConfig, enable_frontend: bool) {
 
     if enable_frontend {
         let generated = generated::generate();
-        let mut scope = web::scope("/");
+        let scope = web::scope("/");
```
Comment (MarinPostma) [inline meilisearch-http/src/lib.rs:150]:
```suggestion
```

you can remove this line, and the one at line 167, since they are now useless

**Review by MarinPostma — DISMISSED** [review]
One small change and we can merge :)

thank you for contributing to MeiliSearch!

**Comment by anirudhRowjee** [comment]
All tests green :) thank you for this opportunity.

**Review by curquiza — APPROVED** [review]
Thank you so much @anirudhRowjee! Especially for your reactivity

If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2021/), and you would like to receive a small gift from MeiliSearch too, please complete [this form](https://meilisearch.typeform.com/to/rPexR5gq).

bors merge

**Review by MarinPostma — APPROVED** [review]
Thanks you!! @curquiza you can merge this pr
