### PR TITLE
Do not commit transaction on failed updates

### LINKED ISSUE #1735: Add documents with wrong primaryKey parameter should not add the primary key to the index
Steps

- Add these documents with the primary key parameter `title`
```
[ {
    "id": 2,
    "title": "Pride and Prejudice",
    "author": "Jane Austin",
    "genre": "romance",
    "price": 3.5
} ]
```
- Check the update: the update fails -> expected ✅
- Get the index: the primary key is added -> unexpected ❌
```
{
    "uid": "indexUID",
    "name": "indexUID",
    "createdAt": "2021-09-29T16:25:03.085943Z",
    "updatedAt": "2021-09-29T16:25:03.088458Z",
    "primaryKey": "title"
}
```
The primary key should not be added.

TLDR; When the first document addition does not work, the primary key passed as parameter should not be added to the index.

⚠️ Add tests

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR fixes MeiliSearch that was always committing the transactions even when an update was invalid and the whole transaction should have been trashed. It was the source of a bug where an invalid update (with an invalid primary key) was creating an index with the specified primary key and should instead have failed and done nothing on the server.

Fixes #1735.

### CODE REVIEW

File: meilisearch-http/tests/index/create_index.rs [hunk 1]
```diff
@@ -33,6 +35,35 @@ async fn create_index_with_primary_key() {
...
+    let res = test::call_service(&app, req).await;
+    assert_eq!(res.status(), 202);
+
+    let index = server.index("movies");
+    index.wait_update_id(0).await;
+
+    let (response, code) = index.get().await;
+    assert_eq!(code, 200);
+    assert_eq!(response["primaryKey"], Value::Null);
+}
```
Comment (MarinPostma) [inline meilisearch-http/tests/index/create_index.rs:65]: can  you use:
```
let server = Server::new();
let index = server.index("test");
index.add_documents(...);
```
instead please? :)

**Review by MarinPostma — CHANGES_REQUESTED** [review]

File: meilisearch-http/tests/index/create_index.rs (hunk 1 above)
Comment (Kerollmops) [reply meilisearch-http/tests/index/create_index.rs]: Fixed, and pushed forced, thank you!

**Review by MarinPostma — APPROVED** [review]
thanks!

bors merge

**Comment by MarinPostma** [comment]
bors merge

**Review by irevoire — APPROVED** [review]

**Comment by irevoire** [comment]
bors merge

**Comment by irevoire** [comment]
good bors :horse:
