### PR TITLE
Store primary key as String when Number exceeds i64 range

### LINKED ISSUE #4696: Valid primary key is refused
**Describe the bug**
When sending a document with a valid primary key I get a message saying my primary key is invalid.

**To Reproduce**
1. `echo '{ "id": 14630868576586246730, "name": "tamo" }' | mieli d a`
2. Document identifier `14630868576586246730` is invalid. A document identifier can be of type integer or string, only composed of alphanumeric characters (a-z A-Z 0-9), hyphens (-) and underscores (_).

**Expected behavior**
It works or returns a better error message

### PR DESCRIPTION
**Pull request by JWSong**
# Pull Request

## Related issue
Fixes #4696 

## What does this PR do?
- When a Number value exceeding the range of i64 is received as a primary key, it will be stored as a String.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

File: meilisearch/tests/documents/add_documents.rs [hunk 1]
```diff
@@ -1040,6 +1040,77 @@ async fn document_addition_with_primary_key() {
...
+      "enqueuedAt": "[date]"
+    }
+    "###);
+
+    index.wait_task(0).await;
+
+    let (response, code) = index.get_task(0).await;
+    snapshot!(code, @"200 OK");
+    snapshot!(json_string!(response, { ".duration" => "[duration]", ".enqueuedAt" => "[date]", ".startedAt" => "[date]", ".finishedAt" => "[date]" }),
+        @r###"
```
Comment (irevoire) [inline meilisearch/tests/documents/add_documents.rs:1072]: I introduced some methods to avoid typos and generally reduce the number of snapshots we do.

```suggestion
    let (response, code) = index.add_documents(documents, Some("primary")).await;
    snapshot!(code, @"202 Accepted");

    let response = index.wait_task(response.uid()).await;
    snapshot!(response,
        @r###"
```

File: meilisearch/tests/documents/add_documents.rs [hunk 2]
```diff
@@ -1040,6 +1040,77 @@ async fn document_addition_with_primary_key() {
...
+    snapshot!(code, @"200 OK");
+    snapshot!(json_string!(response, { ".createdAt" => "[date]", ".updatedAt" => "[date]" }),
+        @r###"
+    {
+      "uid": "test",
+      "createdAt": "[date]",
+      "updatedAt": "[date]",
+      "primaryKey": "primary"
+    }
+    "###);
```
Comment (irevoire) [inline meilisearch/tests/documents/add_documents.rs:1101]: That doesn't give us much information, we can get rid of it I think

```suggestion
```

File: milli/src/documents/primary_key.rs [hunk 3]
```diff
@@ -166,7 +166,7 @@ pub fn validate_document_id_value(document_id: Value) -> StdResult<String, UserE
             Some(s) => Ok(s.to_string()),
             None => Err(UserError::InvalidDocumentId { document_id: Value::String(string) }),
         },
-        Value::Number(number) if number.is_i64() => Ok(number.to_string()),
+        Value::Number(number) if !number.is_f64() => Ok(number.to_string()),
```
Comment (irevoire) [inline milli/src/documents/primary_key.rs:169]: Why did you change the condition from `is_i64` to `is_f64`?

**Review by irevoire — CHANGES_REQUESTED** [review]
Hey @JWSong I think we'll be able to merge quite fast, thanks for the investigation!
I left a few comments

File: milli/src/documents/primary_key.rs (hunk 3 above)
Comment (JWSong) [reply milli/src/documents/primary_key.rs:169]: The `Number` type in JSON can be a float, so without the above guard clause, the document id would allow the character `.`.

Comment (irevoire) [reply milli/src/documents/primary_key.rs:169]: Oh yes I initially missed the new `!`, that’s a neat addition thanks

File: meilisearch/tests/documents/add_documents.rs (hunk 2 above)
Comment (JWSong) [reply meilisearch/tests/documents/add_documents.rs]: applied the suggestion on 6fb36ed30e9bd3768b9a9686606198029d6172b9

**Review by irevoire — APPROVED** [review]
Awesome, thanks a lot @JWSong 

bors merge

**Comment by JWSong** [comment]
Tests on macOS 12 failed. Seems like this isn't related to my change. Could you check it please? @irevoire

**Comment by irevoire** [comment]
Yep, it looks like a flaky test; I’ll try again with bors ;

bors merge
