### PR TITLE
Limit the number of values returned by the facet search

### LINKED ISSUE #4312: The `/facet-search` route doesn't take the `faceting.maxValuesPerFacet` setting
**Describe the bug**
The number of values per facet returned by the `indexes/{index}/facet-search` route is not tacking the `faceting.maxValuePerFacet` setting into account.

**To Reproduce**
1. Send documents with filterable attributes to Meilisearch
2. Call the `facet-search` route and see that it returns 100 values per facet
3. Change the `faceting.maxValuesPerFacet` in the settings to, say, 3
4. Call the `facet-search` route and see that it always returns 100 values per facet

**Expected behavior**
The `faceting.maxValuesPerFacet` must impact the `/facet-search` route.

**Meilisearch version:**
All the version from v1.3 to 1.5.

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR fixes a bug where the number of values per facet returned by the `indexes/{index}/facet-search` route was not tacking the `faceting.maxValuePerFacet` setting. It also adds a test.

Fixes #4312

### CODE REVIEW

File: milli/src/search/mod.rs [hunk 1]
```diff
@@ -27,8 +27,8 @@ static LEVDIST0: Lazy<LevBuilder> = Lazy::new(|| LevBuilder::new(0, true));
 static LEVDIST1: Lazy<LevBuilder> = Lazy::new(|| LevBuilder::new(1, true));
 static LEVDIST2: Lazy<LevBuilder> = Lazy::new(|| LevBuilder::new(2, true));
 
-/// The maximum number of facets returned by the facet search route.
-const MAX_NUMBER_OF_FACETS: usize = 100;
+/// The maximum number of values per facet returned by the facet search route.
+const MAX_NUMBER_OF_VALUES_PAR_FACET: usize = 100;
```
Comment (dureuill) [inline milli/src/search/mod.rs:31]:
```suggestion
const MAX_NUMBER_OF_VALUES_PER_FACET: usize = 100;
```

File: milli/src/search/mod.rs [hunk 2]
```diff
@@ -315,14 +316,25 @@ impl<'a> SearchForFacetValues<'a> {
         search_query: Search<'a>,
         is_hybrid: bool,
     ) -> SearchForFacetValues<'a> {
-        SearchForFacetValues { query: None, facet, search_query, is_hybrid }
+        SearchForFacetValues {
+            query: None,
+            facet,
+            search_query,
+            max_values: MAX_NUMBER_OF_VALUES_PAR_FACET,
```
Comment (dureuill) [inline milli/src/search/mod.rs:323]:
```suggestion
            max_values: MAX_NUMBER_OF_VALUES_PER_FACET,
```

Comment (dureuill) [reply milli/src/search/mod.rs:323]: I'm wondering if we shouldn't call this `DEFAULT_NUMBER_OF_VALUES_PER_FACET` given it is configurable now, but that's a nitpick

**Comment by curquiza** [comment]
To let you know: I changed the milestones since this PR will be merged into `main`

**Comment by Kerollmops** [comment]
@curquiza, that's my bad. I rebased on the `release-v1.6` as I would like to fix this bug for Monday (it's a request of one of our customers).

Thank you @dureuill for your review 🙏

**Review by dureuill — APPROVED** [review]
🚀

**Comment by dureuill** [comment]
bors merge
