### PR TITLE
Fix bad http status and error message on wrong payload 

### LINKED ISSUE #4698: Bad http status and error message on wrong payload
**Describe the bug**
When sending badly formatted payload to meilisearch it returns a « 500 internal error » instead of a user error.
The error message is also quite ugly.

**To Reproduce**
1.`echo "kefir" | http PUT :7700/indexes/12/documents "Content-Type: application/json" "Content-Encoding: gzip"`
2. 
```
HTTP/1.1 500 Internal Server Error
content-encoding: gzip
content-type: application/json
date: Thu, 13 Jun 2024 14:31:37 GMT
transfer-encoding: chunked
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
vary: accept-encoding

{
    "code": "internal",
    "link": "https://docs.meilisearch.com/errors#internal",
    "message": "payload reached EOF before completing: Some(Custom { kind: Other, error: DecompressError(General { msg: None }) })",
    "type": "internal"
}
```

### PR DESCRIPTION
**Pull request by Karribalu**
# Pull Request

## Related issue
Fixes #4698

## What does this PR do?
- Fixes bad http status when bad payload with gzip Content-Encoding

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

File: meilisearch/src/error.rs [hunk 1]
```diff
@@ -98,14 +98,29 @@ impl From<MeilisearchHttpError> for aweb::Error {
...
+                ActixPayloadError::OtherError(error),
+            )),
+        }
     }
 }
 
+#[derive(Debug, thiserror::Error)]
+pub enum ActixPayloadError {
+    #[error("The provided payload is incomplete and cannot be decompressed")]
+    IncompleteError,
```
Comment (irevoire) [inline meilisearch/src/error.rs:115]: Is this error only happening for compressed payloads?

File: meilisearch/src/error.rs [hunk 2]
```diff
@@ -122,13 +137,15 @@ impl ErrorCode for PayloadError {
...
         match self {
             PayloadError::Payload(e) => match e {
-                aweb::error::PayloadError::Incomplete(_) => Code::Internal,
-                aweb::error::PayloadError::EncodingCorrupted => Code::Internal,
-                aweb::error::PayloadError::Overflow => Code::PayloadTooLarge,
-                aweb::error::PayloadError::UnknownLength => Code::Internal,
-                aweb::error::PayloadError::Http2Payload(_) => Code::Internal,
-                aweb::error::PayloadError::Io(_) => Code::Internal,
-                _ => todo!(),
+                ActixPayloadError::IncompleteError => Code::BadRequest,
```
Comment (irevoire) [inline meilisearch/src/error.rs:140]: nice

**Review by irevoire — CHANGES_REQUESTED** [review]
Hey @Karribalu,

Thanks for your interest in the project!
Do you know in which context the `aweb::error::PayloadError::Incomplete(_)` error can be thrown?
If it's not only for compressed payload I'm afraid your new error message is worse than the previous one (which was also bad) 😔 

You're right on the tests, there was no tests on the error message.
You could try to duplicate this one, send bad payload and then snapshot the error messages; https://github.com/meilisearch/meilisearch/blob/534f696b2965c4d601dfcb7c764c2451e852c8c2/meilisearch/tests/documents/add_documents.rs#L127-L185

File: meilisearch/src/error.rs (hunk 1 above)
Comment (Karribalu) [reply meilisearch/src/error.rs:115]: Hey @irevoire,
Thanks for pointing this out,
I have gone through Actix web docs for finding any references,
I don't have any concrete evidence that it will only be thrown in decompression.

Can we add a generalised error message

"The provided payload is incomplete" or 
"The provided payload is incomplete and cannot be parsed"

Comment (irevoire) [reply meilisearch/src/error.rs:115]: >  "The provided payload is incomplete and cannot be parsed"

That seems better than the original one yes

Comment (Karribalu) [reply meilisearch/src/error.rs]: Updated the message and also added the test for it,
Please review and let me know of any more changes

**Review by irevoire — APPROVED** [review]
Thanks @Karribalu that’s perfect 👌 

bors merge
