### PR TITLE
normalize synonyms during indexation

### LINKED ISSUE #1135: Synonym doesn't work as expected
**Describe the bug**
Want to create a one-way synonym for `lotr` to `The Lord of The Rings`. I've learned that there's a limitation for the word-length of synonyms, so I've tried to make one for `JP` -> `Jude Fisher` which is an author in my [dataset](https://gist.githubusercontent.com/michielmulders/0f04916b50c826217b3756a682a09d28/raw/15d2077fd685fe522d19e341da636bdde173fcc2/dataset.json).

**To Reproduce**
1. Create `books` index
2. Upload my dataset
3. Create the above two synonyms. My settings object looks like this;

```js
{ rankingRules:
   [ 'typo',
     'words',
     'proximity',
     'attribute',
     'wordsPosition',
     'exactness' ],
  distinctAttribute: null,
  searchableAttributes: [ '*' ],
  displayedAttributes: [ '*' ],
  stopWords: [],
  synonyms: { JF: [ 'Jude Fisher' ], lotr: [ 'The Lord of the Rings' ] },
  attributesForFaceting: [ 'language' ] }
```

**Expected behavior**
I want to find a couple of `The Lord of the Rings` results that are included in my dataset when searching for `lotr` or `JF`.

Currently, I get an empty result `[]`.

**Desktop (please complete the following information):**
 - OS: Windows 10
- Node: v10.18.1
- Using MeiliSearch sandbox

### PR DESCRIPTION
**Pull request by LegendreM**
fix #1135 #964

Normalizes the synonyms before indexing them, so they are not case sensitive anymore. Then normalization also involves deunicoding is some cases, such as accents, so `été` and `ete` are considered equivalent in a search for synonyms.

### CODE REVIEW

**Comment by LegendreM** [comment]
bors try

File: meilisearch-core/src/update/settings_update.rs [hunk 1]
```diff
@@ -289,13 +290,27 @@ pub fn apply_synonyms_update(
...
+    let stop_words = index.main.stop_words_fst(writer)?.map_data(Cow::into_owned)?;
+    let analyzer = Analyzer::new(AnalyzerConfig::default_with_stopwords(&stop_words));
+
+    fn normalize<T: AsRef<[u8]>>(analyzer: &Analyzer<T>, text: &str) -> String {
+        analyzer.analyze(&text)
+            .tokens()
+            .fold(String::new(), |mut s, t| {
+                s.push_str(&t.word);
+                s
+            })
```
Comment (MarinPostma) [inline meilisearch-core/src/update/settings_update.rs:302]:
```suggestion
            .fold(String::new(), |mut s, t| s + t.text())
```

**Review by MarinPostma — CHANGES_REQUESTED** [review]

**Comment by LegendreM** [comment]
bors try

File: meilisearch-core/src/update/settings_update.rs [hunk 2]
```diff
@@ -289,13 +290,24 @@ pub fn apply_synonyms_update(
 
     let main_store = index.main;
     let synonyms_store = index.synonyms;
+    let stop_words = index.main.stop_words_fst(writer)?.map_data(Cow::into_owned)?;
+    let analyzer = Analyzer::new(AnalyzerConfig::default_with_stopwords(&stop_words));
+
+    fn normalize<T: AsRef<[u8]>>(analyzer: &Analyzer<T>, text: &str) -> String {
+        analyzer.analyze(&text)
+            .tokens()
+            .fold(String::new(), |mut s, t| s + t.text())
```
Comment (MarinPostma) [inline meilisearch-core/src/update/settings_update.rs:299]:
```suggestion
            .fold(String::new(), |s, t| s + t.text())
```

**Review by MarinPostma — CHANGES_REQUESTED** [review]

**Comment by qdequele** [comment]
@LegendreM How Chinese synonyms are handled? Are they also deunidecoded? What about emojis and others?

**Comment by qdequele** [comment]
> @LegendreM How Chinese synonyms are handled? Are they also deunidecoded? What about emojis and others?

After a discussion with @LegendreM, the only Latin based languages will be normalized.

**Comment by LegendreM** [comment]
bors merge

**Review by MarinPostma — APPROVED** [review]
