### PR TITLE
Fix(dumps): Explicitly define serde for time

### LINKED ISSUE #2199: Dumps from v0.25.2 can not be imported to v0.26rc (rc2 and rc3)
A dump created by an instance of meilisearch v0.25.2 can not be used as a dump import in v0.26.0. This behavior has been checked with `v0.26.0rc`, `v0.26.0rc2` and `v0.26.0rc3`

**To Reproduce**
1. Run a v0.25.2 meilisearch instance.
2. Index a few thousand documents
3. Call the `/dumps` route and check that the dump status is "done"
4. Stop v0.25.2 instance (make sure to remove `data.ms` folder just to be sure)
5. run a v0.26rc3 instance with the following command:
```bash
./meilisearch --import-dump <path-to-dump>
```
6. Meilisearch throws an error:
```
Error: a character literal was not valid
```

**Expected behavior**
v0.26.0 should run and it should have indexed all of the documents present in the previous instance and therefore in the dump

### PR DESCRIPTION
**Pull request by ManyTheFish**
fix #2199

### CODE REVIEW

**Review by irevoire — APPROVED** [review]
I missed Rhodes thank you!

File: meilisearch-lib/src/index_controller/dump_actor/mod.rs [hunk 1]
```diff
@@ -268,7 +269,10 @@ fn extract_dump(
 
     let meta_path = tmp_src_path.join(META_FILE_NAME);
     let mut meta_file = File::open(&meta_path)?;
+
+    println!("before load metadata");
     let meta: MetadataVersion = serde_json::from_reader(&mut meta_file)?;
+    println!("after load metadata");
```
Comment (Kerollmops) [inline meilisearch-lib/src/index_controller/dump_actor/mod.rs:275]: _Ça dégage, ça!_

**Review by Kerollmops — CHANGES_REQUESTED** [review]

**Review by Kerollmops — APPROVED** [review]

**Comment by ManyTheFish** [comment]
bors merge
