### PR TITLE
Extend API keys

### LINKED ISSUE #1979: v0.25 RC - QA API Keys
Hi folks 👋

After a first QA session, here are some feedbacks.

## `/keys` access

- The endpoints /keys are accessible without a master key defined for the instance, this API resource should not be accessible without it for security reasons.

## API Key Format 

- The formats of the `createdAt` and `updateAt` fields should be displayed with a precision in seconds (It facilitates reading while the microseconds precision is not needed here). For example, `createdAt: "2021-11-12T10:00:00Z"` instead of `"createdAt": "2021-12-07T14:30:22.633153Z"`.
- If an API key does not have a `description`, the field should be displayed with a `null` value.

## GET `/keys`

- API Key objects should be ordered by `createdAt` in `desc` order. (Most recent first)

## POST `/keys`

- `expiresAt` should be a mandatory field, `null` should be specified for no expiration date.
-  Setting `expiresAt` with `null` throw a validation error
- `expiresAt` if specified should throw an error if it's a past datetime from now. (This behavior is also found on the `patch` method).
-  Omitting the timezone part of the ISO-8601 format  at the end of the `expiresAt` field throws an error of format validation. An omitted timezone should default to `Z` automatically. e.g. Sending `"2021-11-12T10:00:00"`, result in `2021-11-12T10:00:00Z` (This behavior is also found on the `patch` method).

## DELETE `/keys/:key`

- Deleting a key returns a "Parse Error: The server returned a malformed response" on an HTTP client. (Postman in this case). The API key is however well deleted.

## Creating an index does not propagate the newly created index in the `indexes` array

When using this API Key:

```
{
        "description": "My API Key",
        "key": "AIcjX0aG56a0c73984fa2f2b7ac93eb3e33b1e227eb304aa8cfe89d3f25aba1f9c0c781b",
        "actions": [
            "*"
        ],
        "indexes": [
            "test"
        ],
        "expiresAt": "2021-12-07T15:05:00Z",
        "createdAt": "2021-12-07T15:10:42.861041Z",
        "updatedAt": "2021-12-07T17:43:26.936329Z"
}
```

I created an index `new_index` since I have the authorization given by `actions = *`. I expected to find it in the `indexes` array of the API Key. Also, access to the newly created index is not given.

```
{
        "description": "My API Key",
        "key": "AIcjX0aG56a0c73984fa2f2b7ac93eb3e33b1e227eb304aa8cfe89d3f25aba1f9c0c781b",
        "actions": [
            "*"
        ],
        "indexes": [
            "test",
            "newindex"
        ],
        "expiresAt": "2021-12-07T15:05:00Z",
        "createdAt": "2021-12-07T15:10:42.861041Z",
        "updatedAt": "2021-12-07T17:43:26.936329Z"
}
```

### LINKED ISSUE #1995: v0.25.0 RC: Rename `indexes.add` into `indexes.create` in the `actions` list
Following https://github.com/meilisearch/specifications/pull/99

We want to rename `indexes.add` into `indexes.create` in the `actions` list.

@meilisearch/docs-team

### LINKED ISSUE #2001: v0.25.0rc0 default keys appear in different order in /keys response
**Describe the bug**

Some times default admin is first sometimes default search is first. Since there is no way of [correctly fetching the key](https://github.com/meilisearch/product/discussions/337) users might use the positions in the `/keys` return to fetch on or the other. 

```json
[
  {
    "description": "Default Admin API Key (Use it for all other operations. Caution! Do not use it on a public frontend)",
// ..
    "createdAt": "2021-12-14T13:07:39.481680100Z",
    "updatedAt": "2021-12-14T13:07:39.481686500Z"
  },
  {
    "description": "Default Search API Key (Use it to search from the frontend)",
// ..
    "createdAt": "2021-12-14T13:07:39.483968800Z",
    "updatedAt": "2021-12-14T13:07:39.483977Z"
  }
]
```

**To Reproduce**
1. Run multiple times `/keys`
2. Order of default keys changes

**Expected behavior**
They should be ordered

**MeiliSearch version:** v0.25.0rc0

### LINKED ISSUE #2003: v0.25.0 RC: `GET /keys` should order keys by `createdAt` in desc order
According to the spec, the keys when calling `GET /keys` should be ordered by `createdAt` in `desc` order. See: https://github.com/meilisearch/specifications/blob/develop/text/0085-api-keys.md#list-details

- [ ] fix bug
- [ ] 🔥 add tests 🔥

### PR DESCRIPTION
**Pull request by ManyTheFish**
# Pull Request

## What does this PR do?

- Add API keys in snapshots
- Add API keys in dumps
- fix QA #1979

fix #1979
fix #1995
fix #2001
fix #2003

related to #1890

### CODE REVIEW

File: meilisearch-auth/src/key.rs [hunk 1]
```diff
@@ -137,3 +132,30 @@ fn generate_id() -> [u8; KEY_ID_LENGTH] {
...
+        Value::String(string) => DateTime::parse_from_rfc3339(string)
+            .map(|d| d.into())
+            .or_else(|_| {
+                NaiveDateTime::parse_from_str(string, "%Y-%m-%dT%H:%M:%S")
+                    .map(|naive| DateTime::from_utc(naive, Utc))
+            })
+            .or_else(|_| {
+                NaiveDateTime::parse_from_str(string, "%Y-%m-%d")
+                    .map(|naive| DateTime::from_utc(naive, Utc))
+            })
```
Comment (irevoire) [inline meilisearch-auth/src/key.rs:147]: Shouldn't we choose one format and stick to it instead of trying to handle everything? :thinking:

File: meilisearch-http/tests/auth/api_keys.rs [hunk 2]
```diff
@@ -981,6 +990,7 @@ async fn patch_api_key_expiration_date() {
 
     let content = json!({ "expiresAt": "2055-11-13T00:00:00Z" });
 
+    thread::sleep(time::Duration::new(1, 0));
```
Comment (irevoire) [inline meilisearch-http/tests/auth/api_keys.rs:993]:
```suggestion
```

File: meilisearch-http/tests/auth/api_keys.rs [hunk 3]
```diff
@@ -920,6 +928,7 @@ async fn patch_api_key_actions() {
         ],
     });
 
+    thread::sleep(time::Duration::new(1, 0));
```
Comment (irevoire) [inline meilisearch-http/tests/auth/api_keys.rs:931]:
```suggestion
```

File: meilisearch-http/tests/auth/api_keys.rs [hunk 4]
```diff
@@ -845,6 +852,7 @@ async fn patch_api_key_indexes() {
 
     let content = json!({ "indexes": ["products", "prices"] });
 
+    thread::sleep(time::Duration::new(1, 0));
```
Comment (irevoire) [inline meilisearch-http/tests/auth/api_keys.rs:855]:
```suggestion
```

File: meilisearch-http/tests/auth/api_keys.rs [hunk 5]
```diff
@@ -719,6 +725,7 @@ async fn patch_api_key_description() {
     // Add a description
     let content = json!({ "description": "Indexing API key" });
 
+    thread::sleep(time::Duration::new(1, 0));
```
Comment (irevoire) [inline meilisearch-http/tests/auth/api_keys.rs:728]: Why are we sleeping in all these tests if we do not check anything time-related after?

```suggestion
```

**Review by irevoire — CHANGES_REQUESTED** [review]

**Comment by curquiza** [comment]
bors try

**Comment by irevoire** [comment]
When I launch meilisearch without any master-key and try to call the route keys, this is the error I get. Is it normal?
image
It's not super explicit to me :thinking: 

And obviously, if I try to set a specific API key this is what happens:
image

**Comment by curquiza** [comment]
bors merge
