### PR TITLE
Unify facet strings by their normalized value

### LINKED ISSUE #5228: Panicking after trying to delete unknown entries while indexing documents
Meilisearch is panicking while trying to delete an unknown entry from an index database. This has been reported internally, and more information can be found [in this Slack thread](https://meilisearch.slack.com/archives/C05DH9MM7JP/p1736513253729999). From the customer:

> We initially saw the same error (different key) in meilisearch 1.12.1, and then upgraded to 1.12.2 and saw the issue there. It looks like incremental facet indexing was introduced in 1.12.2 - so it sounds like that change can be ruled out.

```
panicked at crates/milli/src/update/new/indexer/mod.rs:586:29: internal error: entered unreachable code: We tried to delete an unknown key: [0, 1, 2, 54, 20, 3, 104, 97, 108, 97, 32, 101, 108, 45, 103, 104, 97, 122, 97, 108, 121]
```

The following is a better error message coming from v1.12.3. It explicitly tells us that the issue comes from deleting an unknown key from the `field-id-docid-facet-strings` database.

```
ERROR meilisearch: info=panicked at crates/milli/src/update/new/indexer/mod.rs:587:29: internal error: entered unreachable code: We tried to delete an unknown key from field-id-docid-facet-strings: "\0\x01\x026\x14\x03hala el-ghazaly"
```

**To Reproduce**
1. Send a lot of documents into an index.
2. Wait for the panic to happen.

**Expected behavior**
Meilisearch shouldn't panic but, more importantly, shouldn't delete unknown entries from the index.

**Meilisearch version:**
v1.12.2

**Additional context**
Meilisearch was running on a Linux.

### PR DESCRIPTION
**Pull request by dureuill**
Fixes #5228: the "missing facet keys" issue.

- Before this PR, updating a document such that `"facet": "DUREUILL"` would become `"facet": "dureuill"` could cause the normalized facet value `dureuill` to be removed from `field_id_docid_facet_strings` db.
- This PR makes sure to unify the intermediate representation of the facet strings by their field_id and **normalized** (and truncated) string value.
- The introduced test is testing only one of the two facet distribution algorithms.
- We removed the panic when the facet string was not found, and we instead returned the normalized string.

## Draft status

- [x] target release v1.12.6 branch and milestone
- [ ] ~consider meilitool offline upgrade to fix the corrupted dbs in the wild.~
   workaround: ~remove facets, then add them again... if your facet distribution is right.~ Just use a dump.
- [x] Add unit test demonstrating the issue fixed by this PR.

### CODE REVIEW

File: crates/milli/src/search/facet/facet_distribution.rs [hunk 1]
```diff
@@ -223,7 +223,7 @@ impl<'a> FacetDistribution<'a> {
                     .index
                     .field_id_docid_facet_strings
                     .get(self.rtxn, &key)?
-                    .unwrap()
+                    .unwrap_or(facet_key)
```
Comment (ManyTheFish) [inline crates/milli/src/search/facet/facet_distribution.rs:226]: Can you add an error log?

Comment (Kerollmops) [reply crates/milli/src/search/facet/facet_distribution.rs]: Fixed, we are now throwing an error log.

**Review by ManyTheFish — APPROVED** [review]
bors merge
