### PR TITLE
Unify "Bad latitude" & "Bad longitude" errors

### LINKED ISSUE #3006: Bad latitude / Bad longitude should share a common message between the invalid sort and invalid filter
**Describe the bug**

- `filter`: `Bad latitude `1000`. Latitude must be contained between -90 and 90 degrees.`
- `sort`: `Latitude must be contained between -90 and 90 degrees.`

We should throw the same error in both case (the one from the filter) => Fixed by #3479

This changes should be done in milli folder.

More information about the expectations
- [ ] If I try to filter on `_geo(x, y, z)` we should trigger the special reserved keywords error 
- [ ] If I try to filter on `_geoDistance(x, y, z)` we should trigger the special reserved keywords error 
- [x] If I try to sort on `_geoRadius(x, y)` we should trigger the special reserved keywords error. Fixed by #3479
- [x] If I try to sort on `_geo(x, y)` we should trigger the special reserved keywords error. Fixed by https://github.com/meilisearch/meilisearch/pull/3631
- [x] If I try to sort on `_geoDistance(x, y)` we should trigger the special reserved keywords error. Fixed by https://github.com/meilisearch/meilisearch/pull/3631

### PR DESCRIPTION
**Pull request by cymruu**
# Pull Request

## Related issue
Fix part of #3006

## What does this PR do?
- Moved out `BadGeoLat`, `BadGeoLng`, `BadGeoBoundingBoxTopIsBelowBottom` from `FilterError` into newly introduced error type `ParseGeoError`. 
- Renamed `BadGeo` error  to `ReservedGeo`
- Used new `ParseGeoError` type in `FilterError` and `AscDescError`

Screenshot: 
image

I ran `cargo test --package milli -- --test-threads 1` and tests passed.
`--test-threads` was set to 1 because my OS complained about too many opened files.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

File: milli/src/asc_desc.rs [hunk 1]
```diff
@@ -162,10 +165,8 @@ impl FromStr for AscDesc {
 
 #[derive(Error, Debug)]
 pub enum SortError {
-    #[error("{}", AscDescError::InvalidLatitude)]
-    InvalidLatitude,
-    #[error("{}", AscDescError::InvalidLongitude)]
-    InvalidLongitude,
+    #[error("{}", error)]
```
Comment (irevoire) [inline milli/src/asc_desc.rs:168]:
```suggestion
    #[error(transparent)]
```

File: milli/src/asc_desc.rs [hunk 2]
```diff
@@ -7,26 +7,29 @@ use serde::{Deserialize, Serialize};
...
+use crate::search::facet::ParseGeoError;
 use crate::{CriterionError, Error, UserError};
 
 /// This error type is never supposed to be shown to the end user.
 /// You must always cast it to a sort error or a criterion error.
 #[derive(Debug)]
 pub enum AscDescError {
-    InvalidLatitude,
-    InvalidLongitude,
+    GeoError(ParseGeoError),
```
Comment (irevoire) [inline milli/src/asc_desc.rs:17]: Hey, this is not mandatory, if you don't want/don't have the time just tell me and I'll do it later.

But it would be nice to use thiserror on this error structure

**Review by irevoire — CHANGES_REQUESTED** [review]
Hey @cymruu, thanks a lot for your contribution; the code is really nice :+1: 

I left one little suggestion + something you can do if you want.
I think clippy is complaining also but overall that's really good :grin:

File: milli/src/asc_desc.rs (hunk 2 above)
Comment (cymruu) [reply milli/src/asc_desc.rs:17]: I'll take care of it and clippy warnings. 
Thank you for reviewing 🙂

**Comment by cymruu** [comment]
I've rebased it on main, sorry for the force push. 
Let me know if I can improve it further :)

**Review by irevoire — CHANGES_REQUESTED** [review]
Hey @cymruu we're almost good!

You just need to run rustfmt one last time and I'll merge your PR :grin: 

(be cautious; we have to use rust nightly to run rustfmt because otherwise, it can't format the imports)

**Review by irevoire — APPROVED** [review]
Nice, I think we're good to merge!
Thanks for cleaning this code 🫶

**Comment by irevoire** [comment]
bors merge
