### PR TITLE
Fix blocking auth

### LINKED ISSUE #2201: Blocking calls in authentication extractor
Reviewing the auth implementation, I found that blocking calls to heed were performed in the implementation of the extractor.

- [blocking calls](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-auth/src/lib.rs#L54-L58) are made in async contexts.
- [`FromRequest`](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-http/src/extractors/authentication/mod.rs#L37) should not return a `Ready` future, but a custom future, encapsulating the authentication action. a boxed future should do the trick, but it should be possible to do it more elegantly.

### PR DESCRIPTION
**Pull request by MarinPostma**
Fix auth blocking runtime

I have decided to remove async code from `meilisearch-auth` and let `meilisearch-http` handle that.

Because Actix polls the extractor futures concurrently, I have made a wrapper extractor that forces the errors from the futures to be returned sequentially (though is still polls them sequentially).
close #2201

### CODE REVIEW

File: meilisearch-http/src/extractors/authentication/mod.rs [hunk 1]
```diff
@@ -2,28 +2,85 @@ mod error;
...
+            },
+            None => Err(AuthenticationError::MissingAuthorizationHeader.into()),
+        }
+    }
+
+    async fn authenticate<S>(
+        auth: AuthController,
+        token: S,
+        index: Option<String>,
+    ) -> Result<(S, Option<AuthFilter>), ResponseError>
```
Comment (ManyTheFish) [inline meilisearch-http/src/extractors/authentication/mod.rs:69]: We may return only an `Option<AuthFilter>`, this would simplify the upper functions.

**Review by ManyTheFish — CHANGES_REQUESTED** [review]
We may not release this in the v0.26, we may instead merge it in `main`

File: meilisearch-http/src/extractors/sequential_extractor.rs [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+        },
+        Done {
+            output: Res,
+        },
+        Error {
+            error: Err,
+        },
+        Empty,
+    }
+}
```
[the remark this answers is not in the document]
Comment (MarinPostma) [reply meilisearch-http/src/extractors/sequential_extractor.rs:148]: it's not, i took inspiration from actix implementation, bu this is my code

[the remark this answers is not in the document]
Comment (ManyTheFish) [reply meilisearch-http/src/extractors/sequential_extractor.rs:148]: Why do you need `#![allow(non_snake_case)]` at the top of the file?

**Review by irevoire — COMMENTED** [review]
The test of the rust-sdk all pass :+1:

File: meilisearch-http/src/extractors/sequential_extractor.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (MarinPostma) [reply meilisearch-http/src/extractors/sequential_extractor.rs:148]: this is because the fields of the generated `SeqFromRequestFutX` are named after the generic type of the field (`A`, `B`,...), and rust complains because they are not snake case

File: meilisearch-http/src/routes/api_key.rs [hunk 3]
```diff
@@ -52,8 +65,13 @@ pub async fn get_api_key(
...
     path: web::Path<AuthParam>,
 ) -> Result<HttpResponse, ResponseError> {
-    let key = auth_controller.get_key(&path.api_key).await?;
-    let res = KeyView::from_key(key, &auth_controller);
+    let api_key = path.into_inner().api_key;
+    let res = tokio::task::spawn_blocking(move || -> Result<_, AuthControllerError> {
+        let key = auth_controller.get_key(&api_key)?;
+        Ok(KeyView::from_key(key, &auth_controller))
+    })
+    .await
```
[the remark this answers is not in the document]
Comment (MarinPostma) [reply meilisearch-http/src/routes/api_key.rs:73]: async auth does not actually do anything related to async, so it made more sense to move te boundary over to meilisearch-http

[the remark this answers is not in the document]
Comment (ManyTheFish) [reply meilisearch-http/src/routes/api_key.rs:73]: OOOOOKKK... My bad, I misunderstood the behavior of `async`, thanks!

File: meilisearch-http/src/extractors/authentication/mod.rs (hunk 1 above)
Comment (ManyTheFish) [reply meilisearch-http/src/extractors/authentication/mod.rs:69]: no sorry, I was saying:
```suggestion
    ) -> Result<Option<AuthFilter>, ResponseError>
```

Is it possible ?

Comment (MarinPostma) [reply meilisearch-http/src/extractors/authentication/mod.rs:69]: no, we need S to be static here, so it could force a clone. This is the only way to report errors without having to clone each time on line 44.

**Review by curquiza — COMMENTED** [review]
Works with the Rust, PHP, Python, Ruby and JS SDK tests 💪 🎉

File: meilisearch-http/src/extractors/authentication/mod.rs (hunk 1 above)
Comment (Kerollmops) [reply meilisearch-http/src/extractors/authentication/mod.rs:69]: On the lines 113, 114 and 115 you clone a lot, maybe you can simplify this method and also clone this token?

File: meilisearch-http/src/extractors/sequential_extractor.rs [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+pub struct SeqHandler<H>(pub H);
+
+pub struct SeqFromRequest<T>(T);
+
+/// This macro implements `FromRequest` for arbitrary arity handler, except for one, which is
+/// useless anyway.
+macro_rules! gen_seq {
+    ($ty:ident; $($T:ident)+) => {
+        pin_project! {
+            pub struct $ty<$($T: FromRequest), +> {
```
Comment (Kerollmops) [inline meilisearch-http/src/extractors/sequential_extractor.rs:21]: Maybe you can put this allow non_snake_case on the struct instead?

File: meilisearch-http/src/extractors/sequential_extractor.rs [hunk 5]
```diff
@@ -0,0 +1,148 @@
+#![allow(non_snake_case)]
+use std::{future::Future, pin::Pin, task::Poll};
+
+use actix_web::{dev::Payload, FromRequest, Handler, HttpRequest};
+use pin_project_lite::pin_project;
+
+/// `SeqHandler` is an actix `Handler` that enforces that extractors errors are returned in the
+/// same order as they are defined in the wrapped handler. This is needed because, by default, actix
+/// to resolves the extractors concurrently, whereas we always need the authentication extractor to
```
Comment (Kerollmops) [inline meilisearch-http/src/extractors/sequential_extractor.rs:9]:
```suggestion
/// resolves the extractors concurrently, whereas we always need the authentication extractor to
```

**Review by Kerollmops — CHANGES_REQUESTED** [review]

File: meilisearch-http/src/extractors/sequential_extractor.rs (hunk 4 above)
Comment (MarinPostma) [reply meilisearch-http/src/extractors/sequential_extractor.rs:21]: not possible, you also get the lint when referring to those fields, it needs to be a module level lint here

File: meilisearch-http/src/extractors/authentication/mod.rs (hunk 1 above)
Comment (MarinPostma) [reply meilisearch-http/src/extractors/authentication/mod.rs:69]: The issue is not about cloning when it's needed, as it is on the lines you mention, but cloning when it is not, for error handling....

But ultimately, passing the token seems useless, I think it's better to just stop passing I it to the `InvalidToken`

**Review by Kerollmops — APPROVED** [review]
Looks good to me!

**Review by ManyTheFish — APPROVED** [review]
